apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      preview.bibsonomy.org/branch: PREVIEW_BRANCH
  template:
    metadata:
      labels:
        preview.bibsonomy.org/branch: PREVIEW_BRANCH
