var LocalizedStrings = { 
   "system.desc" : "Lesezeichen und Referenzen teilen - in blau!",
   "system.about" : "Mit {0} lassen sich einfach und komfortabel Lesezeichen und Publikationen online verwalten und teilen.",
   "system.contact" : "Kontakt:",
   "system.groups" : "Um eine Gruppe zum System hinzuzufügen, registrieren Sie bitte einen \\",
   "<a href" : "\"mailto:webmaster@bibsonomy.org\">webmaster@bibsonomy.org</a>. \\",
   "<a href" : "\"http://bibsonomy.blogspot.com/2007/08/feature-of-week-manage-publication.html\"> \\",
   "<a href" : "\"http://bibsonomy.blogspot.com/2007/08/feature-of-week-manage-publication.html\"> \\",
   "and	<a href" : "\"http://bibsonomy.blogspot.com/2007/04/feature-of-week-groups-and-friends.html\"> \\",
   "feeds.bookmark" : "Lesezeichen RSS-Feed für",
   "feeds.publication" : "Publikationen RSS-Feed für",
   "feeds.burst" : "Publikationen Burst-RSS-Feed für",
   "feeds.swrc" : "SWRC-Ausgabe für",
   "navi.tags" : "Tags",
   "navi.authors" : "Autoren",
   "navi.groups" : "Gruppen",
   "navi.group.cap" : "Gruppen",
   "navi.relations" : "Relationen",
   "navi.popular" : "Beliebt",
   "navi.relations.cap" : "Relationen",
   "navi.my" : "mein",
   "navi.my.plural" : "meine",
   "navi.friend" : "Freund",
   "navi.friends" : "Freunde",
   "navi.friends.cap" : "Freunde",
   "navi.search.cap" : "Suche",
   "navi.pdfs" : "PDFs",
   "navi.duplicates.cap" : "Duplikate",
   "navi.bibtex.cap" : "BibTeX",
   "navi.postBookmark" : "Lesezeichen eintragen",
   "navi.postPublication" : "Publikation eintragen",
   "navi.loggedInAs" : "angemeldet als",
   "navi.help" : "Hilfe",
   "navi.helpUrl" : "/help_de",
   "navi.blog" : "Weblog",
   "navi.about" : "Über uns",
   "navi.pickedIn" : "hinzugefügt zur",
   "navi.basket" : "Ablage",
   "navi.editTags" : "Tags bearbeiten",
   "navi.editBookmark" : "Lesezeichen bearbeiten",
   "navi.settings" : "Einstellungen",
   "navi.logout" : "Abmelden",
   "navi.login" : "Anmelden",
   "navi.register" : "Registrieren",
   "navi.username" : "Benutzername",
   "navi.password" : "Passwort",
   "navi.gender" : "Geschlecht",
   "navi.place" : "Ort",
   "navi.tag" : "Tag",
   "navi.user" : "Benutzer",
   "navi.group" : "Gruppe",
   "navi.viewable" : "Sichtbar",
   "navi.author" : "Autor",
   "navi.concept" : "Konzept",
   "navi.bibtexkey" : "BibTeX key",
   "navi.search" : "Suche",
   "navi.all" : "alles",
   "navi.join" : "der Gruppe {0} beitreten",
   "navi.admin" : "Administrator",
   "navi.search.hint" : "<hier Volltext-Suche eingeben>",
   "navi.tag.hint" : "<Tag(s) eingeben>",
   "navi.user.hint" : "<Benutzername eingeben>",
   "navi.group.hint" : "<Gruppen eingeben>",
   "navi.author.hint" : "<Autoren eingeben>",
   "navi.concept.hint" : "<Konzept-Tags eingeben>",
   "navi.bibtexkey.hint" : "<BibTeX-key eingeben>",
   "navi.passReminder.button" : "Senden",
   "navi.passReminder" : "Passwort-Erinnerung",
   "navi.passChangeOnRemind" : "Passwort-Änderung",
   "navi.export" : "Export",
   "navi.mysearch" : "Meine Suche",
   "navi.relevantFor" : "interessantFür",
   "mysearch.header" : "Durchsuche mein Bibsonomy",
   "mysearch.option.header" : "Suchoptionen",
   "mysearch.option.tag" : "Tags",
   "mysearch.option.author" : "Autoren",
   "mysearch.option.result.header" : "Suchergebnisse",
   "mysearch.option.filter" : "Filter:",
   "mysearch.option.filter.text" : "<Titel, Autoren oder Tags hier eingeben>",
   "mysearch.option.result.lang" : "Ergebnisse",
   "export.header" : "Publikationsexport",
   "export.format" : "Format",
   "export.info" : "Durch Auswahl eines der Formate lassen sich die Publikationen von {0} in das \\",
   "                  <a href" : "\"http://en.wikipedia.org/wiki/LaTeX\">LaTeX</a>. \\",
   "                 <a href" : "\"http://www.cs.vu.nl/~pmika/research/burst/BuRST.html\">BuRST</a>-Spezifikation. \\",
   "                 Dies ist ein gültiger <a href" : "\"http://en.wikipedia.org/wiki/RSS\">RSS</a> Feed welchen Sie \\",
   "                <a href" : "\"http://ontoware.org/projects/swrc/\">SWRC</a>-Ontologie.                 ",
   "                  welches auf der <a href" : "\"/settings\">settings</a>-Seite hochgeladen werden \\",
   "                  <a href" : "\"http://jabref.sourceforge.net/help/CustomExports.php\">hier</a>.",
   "benutzerdefinierte Filter auf der <a href" : "\"/settings\">Einstellungs-Seite</a> hochzuladen. \\",
   "<a href" : "\"http://jabref.sourceforge.net/help/CustomExports.php\">hier</a>.",
   "export.bibtex.record" : "BibTeX Eintrag",
   "export.endnote.record" : "Endnote Eintrag",
   "basket.info" : "Hier können Sie Publikations-Eintrage, welche Sie mittels des \"merken\"-Links zur Ablage \\",
   "hinzugefügt haben verwalten. Weitere Informationen dazu finden Sie <a href" : "\"/help_de/basic/firststeps#basket\">hier</a>.",
   "basket.groupmetadata" : "Metadaten editieren für die Gruppe",
   "basket.removeAll" : "alle aus Ablage entfernen",
   "basket.removeAllVerbose" : "alle Publikationen aus der Ablage entfernen",
   "batchedit.info" : "Hier können Sie Ihre Einträge bearbeiten",
   "batchedit.allTags" : "Diese Tags werden zu <strong>ALLEN</strong> Einträgen auf dieser Seite hinzugefügt!",
   "batchedit.deleteAll" : "alle Einträge löschen",
   "batchedit.deleteAll.confirm" : "Wollen Sie wirklich alle Einträge zum Löschen markieren?",
   "batchedit.button.update" : "absenden",
   "batchedit.yourTags" : "Ihre Tags",
   "batchedit.yourPosts" : "Ihre Einträge",
   "batchedit.deletePostQ" : "Eintrag löschen?",
   "batchedit.deletePost" : "Eintrag löschen",
   "batchedit.disregardedPosts" : "Ignorierte Einträge",
   "batchedit.disregardedPosts.info" : "Die folgenden Einträge gehören nicht Ihnen und daher können Sie sie nicht ändern.",
   "friends.friendof" : "Sie sind ein Freund von",
   "friends.yourfriends" : "Ihre Freunde sind",
   "friends.addfriend" : "Einen Freund hinzufügen",
   "friends.button.add" : "hinzufügen",
   "friends.actions.delete.title" : "{0} von Ihrer Freundesliste entfernen",
   "friends.actions.delete" : "entfernen",
   "bibtex.actions.pick" : "merken",
   "bibtex.actions.pick.title" : "diese Publikation zur Ablage hinzufügen",
   "bibtex.actions.unpick" : "entfernen",
   "bibtex.actions.unpick.title" : "diese Publikation aus der Ablage entfernen",
   "bibtex.actions.copy" : "kopieren",
   "bibtex.actions.copy.title" : "diese Publikation in die eigene Sammlung kopieren",
   "bibtex.actions.editTags" : "taggen",
   "bibtex.actions.editTags.title" : "die Tags dieser Publikation bearbeiten",
   "bibtex.actions.edit" : "bearbeiten",
   "bibtex.actions.edit.title" : "diese Publikation bearbeiten",
   "bibtex.actions.delete" : "löschen",
   "bibtex.actions.delete.title" : "diese Publikation aus der eigenen Sammlung löschen",
   "bibtex.actions.url" : "URL",
   "bibtex.actions.url.title" : "diese Publikation enthält eine URL, die hier verlinkt ist",
   "bibtex.actions.bibtex" : "BibTeX",
   "bibtex.actions.bibtex.title" : "diese Publikation im BibTeX-Format anzeigen",
   "bibtex.actions.openurl" : "openURL",
   "bibtex.actions.openurl.title" : "eine Anfrage an den openURL-Server mit dem Metadaten dieser Publikation senden",
   "bibtex.actions.additional_url.add" : "hinzuf&uuml;gen",
   "bibtex.actions.additional_url.add.title" : "eine weitere zus&auml;tzliche URL hinzuf&uuml;gen",
   "bibtex.actions.additional_url.delete" : "l&ouml;schen",
   "bibtex.actions.additional_url.delete.title" : "diese zus&auml;tzliche URL l&ouml;schen",
   "bibtex.actions.private_document.upload" : "Hochladen",
   "bibtex.actions.private_document.download" : "Herunterladen",
   "bibtex.actions.private_document.delete" : "l&ouml;schen",
   "bibtex.actions.private_document.description" : "Ihr privates Dokument zu diesem Eintrag",
   "bibtex.actions.private_document.upload.title" : "Eine privates Dokument (PDF, PS, ...) zu diesem Eintrag hochladen",
   "bibtex.actions.tags.update" : "Tags aktualisieren",
   "bibtex.edition" : "Edition",
   "bibtex.pages" : "Seite",
   "bibtex.volume" : "Volume",
   "bibtex.volumeOf" : "von",
   "bibtex.url" : "URL",
   "bibtex.abstract.cap" : "Zusammenfassung",
   "bibtex.abstract" : "Zusammenfassung",
   "bibtex.additional_urls" : "Zus&auml;tzliche URLs",
   "bibtex.editors.abbr" : "Eds.",
   "bibtex.resources" : "Resourcen (URL, PDF, PS...)",
   "bibtex.private_note" : "Private Notiz",
   "bibtex.upload.file.label" : "Ihre private Kopie des Dokuments",
   "bibtex.upload.file.button" : "Hinzufügen",
   "bibtex.upload.file.helptext" : "Hier können Sie ein Dokument an Ihren Eintrag anhängen. Wählen Sie eine Datei aus und klicken Sie dann auf \"Hinzufügen\".",
   "bibtex.upload.file.success" : "Die Datei wurde erfolgreich hochgeladen.",
   "bibtex.upload.file.hash" : "Md5-Hashwert des Dateiinhalts",
   "bibtex.upload.file.back" : "Zurück",
   "bibtex.upload.file.page" : "Datei Upload",
   "bibtex.upload.file.link" : "Datei hochladen",
   "bibtex.details.owner" : "Eintrag von",
   "bibtex.citation_format" : "Zitationsstil",
   "bibtex.all_exports" : "alle Formate",
   "bibtex.all_exports.title" : "alle verf&uuml;gbaren Formate (RSS, CVS, ...) anzeigen",
   "bookmark.actions.edit" : "bearbeiten",
   "bookmark.actions.edit.title" : "dieses Lesezeichen bearbeiten",
   "bookmark.actions.editTags" : "taggen",
   "bookmark.actions.editTags.title" : "die Tags dieses Lesezeichens bearbeiten",
   "bookmark.actions.delete" : "löschen",
   "bookmark.actions.delete.title" : "dieses Lesezeichen aus der Sammlung löschen",
   "bookmark.actions.copy" : "kopieren",
   "bookmark.actions.delete.title" : "dieses Lesezeichen in die eigene Sammlung kopieren",
   "list.total" : "total",
   "meta.lang" : "de",
   "meta.author" : "Fachgebiet Wissensverarbeitung, Universität Kassel",
   "meta.copyright" : "Fachgebiet Wissensverarbeitung, Universität Kassel",
   "meta.keywords" : "BibTeX, Bookmarks, Folksonomy, Tagging, Wissensverarbeitung, Wissensmanagement, Data Mining, Informatik, Universität Kassel",
   "meta.description" : "Webapplikation des Fachgebiets Wissensverarbeitung, Universität Kassel",
   "user.settings.realname" : "Realname",
   "user.settings.email" : "E-Mail",
   "user.settings.homepage" : "Homepage",
   "user.settings.passwordCheck" : "Passwort",
   "user.settings.openid" : "OpenID",
   "user.settings.birthday" : "Geburtsdatum",
   "user.tmp.password" : "Temporäres Passwort",
   "reminder.helptext" : "Wenn Sie Ihr Passwort vergessen haben, besteht hier die Möglichkeit ein neues Passwort für Ihren Account anzufordern. Sie erhalten daraufhin eine Email mit dem automatisch generierten Passwort, welches Sie beim nächsten Einloggen nutzen können.",
   "register.success" : "Sie haben sich erfolgreich als Benutzer {0} angemeldet!",
   "register.welcome" : "Willkommen bei ",
   "register.signedIn" : "Sie haben sich erfolgreich angemeldet.",
   "register.nextSteps" : "Nächste Schritte:",
   "register.nextSteps.step1" : "Ziehen Sie diese Schaltflächen in die Linkleiste Ihres Browsers.",
   "register.nextSteps.step2.surf" : "Besuchen Sie Ihre Lieblingsseite und speichern Sie ein Lesezeichen indem Sie auf die gerade hinzugefügte \"Lesezeichen eintragen\" Schaltfläche klicken.",
   "register.nextSteps.step2.click" : "Ein anschließender Klick auf \"mein{0}\" zeigt Ihnen Ihr erstes erfolgreich eingetragenes Lesezeichen. ",
   "register.confirmationMail" : "Eine Bestätigung wurde an Ihre E-Mail-Adresse gesendet.",
   "register.internetExplorer" : "Im Internet Explorer müssen Sie mit der rechten Maustaste auf die Schaltfläche klicken und \"zu Favoriten hinzufügen\" auswählen. Weitere Informationen ",
   "register.internetExplorer.here" : "hier",
   "register.dragButtons" : "Ziehen Sie die Schaltflächen mit der Maus in die Linkleiste Ihres Browsers.",
   "register.openid.hint1" : "Alternativ können Sie sich  ",
   "register.openid.hint2" : "mit Ihrer OpenID registrieren. ",
   "register.openid.hint3" : "Es ist einfacher und Sie brauchen sich keinen weiteren Benutzernamen und Passwort merken.",
   "register.notice.openid" : "Registrieren Sie sich bei BibSonomy mit Ihrer OpenID",
   "register.openid.example" : "(z.B. http://username.myopenid.com)",
   "register.openid.desc.title" : "Was ist OpenID?",
   "register.openid.desc" : "OpenID ist ein neuer offener Standard, mit dem Sie sich auf Websites über nur eine URL anmelden können,\\n\\",
   "register.openid.required" : "Pflichtfelder",
   "register.openid.optional" : "Optionale Angaben",
   "register.openid.step1" : "Schritt 1 - Geben Sie im unteren Feld Ihre OpenID ein",
   "register.openid.step2" : "Schritt 2 - Profildaten bearbeiten",
   "post.bookmark.edit.existent" : "Hinweis: Sie bearbeiten einen existierenden Eintrag!",
   "post.resource.public" : "öffentlich",
   "post.resource.private" : "privat",
   "post.resource.other" : "andere",
   "post.resource.relevantfor" : "Interessant für",
   "post.resource.viewablefor" : "Sichtbar für",
   "post.resource.requiredfield" : "Pflichtfeld",
   "post.resource.url" : "URL",
   "post.resource.title" : "Titel",
   "post.resource.description" : "Beschreibung",
   "post.resource.description.cap" : "Beschreibung",
   "post.resource.comment" : "Kommentar",
   "post.resource.tags" : "Tags",
   "post.resource.tags.comma" : "Bitte bestätigen Sie, dass Sie Komma/Semikolon in den Tags verwenden möchten. ",
   "post.resource.copytags" : "Tags des kopierten Posts ",
   "post.resource.recommendation" : "Empfehlung",
   "post.resource.waitingForTags" : "Hole Tag-Vorschläge",
   "post.resource.reloadRecommendation" : "neue Vorschläge holen",
   "post.resource.suggested" : "Vervollständigung",
   "post.resource.spaceseperated" : "mit Leerzeichen getrennt",
   "post.resource.editbookmark" : "Bearbeiten Sie ihr Lesezeichen nach Belieben",
   "post.resource.aboutrelevantfor" : "Fügen sie Tags hinzu, welche beschreiben in wie fern ihr Post relevant für einige Gruppen ist.",
   "post.resource.about" : "Über dieses Feld",
   "post.resource.relevant" : "Wählen Sie eine oder mehrere Gruppen aus für die ihr Post interressant sein könnte. ",
   "post.resource.notagset" : "Es sind noch keine Tagmengen für diese Gruppe vorhanden.",
   "post.resource.go" : "Los!",
   "post.resource.bookmark_a_publication" : "Die Seite die Sie speichern wollen enthält folgende Publikationsreferenz",
   "post.resource.spaceseparated" : "durch Leerzeichen getrennt",
   "mail.registration.subject " : " Ihre {1} Registrierung",
   "mail.registration.body " : " \\n\\",
   "mail.reminder.subject" : "Ihre {1} Passwort Anfrage",
   "mail.reminder.body" : "\\n\\",
   "login.notice.welcome_1" : "Willkommen bei ",
   "login.notice.welcome_2" : "einem System zum Verwalten und Teilen von Lesezeichen und Publikationsreferenzen.",
   "login.notice.welcome_3" : "Loggen Sie sich dazu ein oder ",
   "login.notice.welcome_4" : "erstellen Sie ein neues Benutzerkonto",
   "login.lostPassword" : "Passwort vergessen",
   "login.lostPassword_1" : "Ich habe mein Passwort vergessen.",
   "login.lostPassword_2" : "Bitte senden Sie mir ein neues Passwort.",
   "login.notRegistered_1" : "Ich habe mich noch nicht registriert, möchte dies aber ",
   "login.notRegistered_2" : "jetzt tun",
   "login.withOpenID" : "Mit OpenID anmelden",
   "login.withUsernameAndPassword" : "Mit Benutzername und Passwort anmelden",
   "login.notice.post.publication" : "Sie versuchen, eine Publikationsreferenz von einer externen Webseite zu speichern.",
   "login.notice.post.bookmark" : "Sie versuchen, ein Lesezeichen zu speichern.",
   "buttons.myProject.title" : "Ziehen Sie diese Schaltfläche in die Linkleiste Ihres Browsers.",
   "buttons.javascript" : "Für diese Funktion müssen Sie JavaScript in Ihrem Browser aktivieren.",
   "error" : "Fehler",
   "publications" : "Publikationen",
   "friends" : "Freunde",
   "bookmarks" : "Lesezeichen",
   "posts" : "Einträge",
   "post" : "Eintrag",
   "tags" : "Tags",
   "busytags" : "beliebte Tags",
   "tag" : "Tag",
   "relatedtags" : "verwandte Tags",
   "similartags" : "ähnliche Tags",
   "and" : "und",
   "members" : "Mitglieder",
   "user" : "Benutzer",
   "users" : "Benutzer",
   "users.similar" : "&auml;hnliche Benutzer",
   "users.similar.for" : "{0}&#39;s &auml;hnliche Benutzer",
   "friend" : "Freund",
   "relatedusers" : "verwandte Benutzer",
   "statistic" : "Statistik",
   "captcha" : "Captcha",
   "submit" : "Abschicken",
   "additional" : "zusätzliche",
   "available" : "verfügbar",
   "days" : "Tage",
   "for" : "für",
   "name" : "Name",
   "create" : "erstellen",
   "save" : "speichern",
   "show" : "anzeigen",
   "hide" : "verbergen",
   "group" : "Gruppe",
   "description" : "Beschreibung",
   "privacy" : "Privacy",
   "general" : "allgemeine Informationen",
   "resetbutton" : "Zurücksetzen",
   "by" : "von",
   "text" : "Text",
   "change" : "&auml;ndern",
   "plain" : "einfach",
   "tags.of_resource" : "Tags zu diesem Eintrag",
   "tags.highlighted.by_user" : "'s Tags hervorgehoben",
   "personalize" : "personalisieren",
   "personalized" : "personalisiert",
   "form.input.select" : "--Bitte wählen--",
   "previous" : "&lt;",
   "first" : "&lt;&lt;",
   "goto.previous" : "zur vorherigen Seite wechseln",
   "goto.first" : "zur ersten Seite wechseln",
   "next" : "&gt;",
   "last" : "&gt;&gt;",
   "goto.next" : "zur nächsten Seite wechseln",
   "goto.last" : "zur letzten Seite wechseln",
   "post.meta.taggedTo" : "als",
   "post.meta.taggedBy" : "von",
   "post.meta.otherPerson" : "weiterem Benutzer",
   "post.meta.otherPeople" : "weiteren Benutzern",
   "post.meta.taggedOn" : "am",
   "post.meta.asGroup" : "zur Gruppe",
   "post.meta.edit" : "bearbeiten",
   "post.meta.edit.title" : "alle eigenen Posts in dieser Liste bearbeiten",
   "post.meta.pick" : "merken",
   "post.meta.pick.title" : "alle Publikationen dieser Seite in die Ablage legen",
   "post.meta.unpick" : "vergessen",
   "post.meta.unpick.title" : "alle Publikationen dieser Seite aus der Ablage entfernen",
   "post.meta.duplicates" : "Alle Ihre Publikationen, die mindestens zweimal vorkommen",
   "post.meta.documents" : "Alle Ihre Publikationen mit Dokumenten im Anhang (PDF, PS oder DJVU)",
   "post.meta.add" : "Hinzufügen  ",
   "post.meta.flag_as_spam.title" : "Diesen Eintrag als Spam markieren",
   "post.meta.flag_as_spam" : "Spam",
   "post.meta.unflag_as_spam.title" : "Diesen Eintrag als keinen Spam markieren",
   "post.meta.unflag_as_spam" : "kein Spam",
   "post.meta.kill_spammer" : "KillSpammer!",
   "post.meta.own_post" : "Sie besitzen dieses Post bereits.",
   "post.meta.copy_this_post" : "Post kopieren.",
   "post.meta.save_as_publication" : "Als Publikation speichern",
   "post.meta.save_as_bookmark" : "Als Lesezeichen speichern",
   "post.meta.recommended" : "Empfehlung",
   "list.show" : "Zeige",
   "list.entriesPerPage" : "pro Seite",
   "tagbox.alph" : "Alpha",
   "tagbox.freq" : "Freq",
   "tagbox.cloud" : "Wolke",
   "tagbox.list" : "Liste",
   "tagbox.minfreq" : "Minfreq",
   "tagrelations" : "Relationen",
   "tagrelations.user.title" : "Alle Relationen dieses Benutzers anzeigen",
   "tagrelations.group.title" : "Alle Relationen dieser Gruppe anzeigen",
   "tagrelations.all.title" : "Alle Relationen anzeigen",
   "tagrelations.showAll" : "alle anzeigen",
   "tagrelations.showAll.title" : "alle Relationen anzeigen",
   "tagrelations.hideAll" : "alle verbergen",
   "tagrelations.hideAll.title" : "alle Relationen verbergen",
   "tagrelations.hide" : "&darr;",
   "tagrelations.hide.title" : "Relation verbergen",
   "tagrelations.showPostsForConcept.title" : "Alle Einträge anzeigen, die mit {0} oder dessen Subtag bezeichnet sind",
   "tagrelations.show.itemspercount" : "Aktuell werden {0} Konzepte pro Seite angezeigt.",
   "tagrelations.show.itemspercount.count" : "Zeige {0}, {1}, {2}, {3} Konzepte pro Seite.",
   "tag.asConceptFromAll" : "als Konzept von allen Benutzern",
   "tag.asConceptFrom" : "als Konzept von",
   "tag.asTagFrom" : "als Tag von",
   "tag.asTagFromAll" : "als Tag von allen Benutzern",
   "tag.asConceptFromGroup" : "als Konzept der Gruppe",
   "tag.asTagFromGroup" : "als Tag der Gruppe",
   "tag.addRelatedTag" : "+",
   "tag.relatedness" : "Verbundenheit",
   "sort.orderBy" : "sortiert nach",
   "sort.date" : "Datum",
   "sort.folkrank" : "FolkRank",
   "sort.folkrank.weight" : "Gewicht",
   "filter" : "Filter",
   "filter.none" : "aus",
   "filter.justPdf" : "nur mit PDF",
   "error.user_page_without_username" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Benutzerseite zuzugreifen, verwenden Sie bitte das URL-Schema /user/USERNAME.",
   "error.friend_page_without_friendname" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Freundeseite zuzugreifen, verwenden Sie bitte das URL-Schema /friend/FRIENDNAME.",
   "error.viewable_page_not_logged_in" : "Für die Anzeige dieser Seite ist es nötig, im System angemeldet zu sein.",
   "error.viewable_page_not_logged_in" : "Für die Anzeige dieser Seite ist es nötig, im System angemeldet zu sein. Wir benötigen diese Information, um Zugang zu Ihren Gruppenmitgliedschaften zu haben. Um die öffentlichen Posts einer Gruppe anzuzeigen, verwenden Sie bitte das Schema /group/GRUPPENNAME",
   "error.viewable_page_without_group" : "Diese Seite existiert leider nicht auf unserem Server. Um Einträge anzuzeigen, deren Sichtbarkeit auf die Gruppe GRUPPENNAME gesetzt ist, verwenden Sie bitte das URL-Schema /viewable/GRUPPENNAME.",
   "error.search_more_than_one_user" : "Sie können leider nur in den Einträgen eines Benutzers suchen.",
   "error.search_page_without_search" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Suchseite zuzugreifen, verwenden Sie bitte das URL-Schema /search/SEARCHNAME.",
   "error.order_not_supported" : "Die angeforderte Sortierung wird vom System nicht unterstützt. Wir bieten momentan die Sortierungen \"added\", \"folkrank\" und \"popular\" an.",
   "error.bibtexkey_no_key" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Seite mit Bibtex-Einträgen zuzugreifen, verwenden Sie bitte das URL-Schema /bibtexkey/KEY.",
   "error.url_no_hash" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Seite mit Url-Einträgen zuzugreifen, verwenden Sie bitte das URL-Schema /url/HASH.",
   "error.bibtex_no_hash" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Seite mit Bibtex-Einträgen zuzugreifen, verwenden Sie bitte das URL-Schema /bibtex/HASH.",
   "error.author_page_without_authorname" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Autor-Seite zuzugreifen, verwenden Sie bitte das URL-Schema /author/AUTHORNAME",
   "error.concept_page_without_conceptname" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Konzept-Seite zuzugreifen, verwenden Sie bitte das URL-Schema /concept/tag/CONCEPT oder /concept/user/USERNAME/CONCEPTNAME",
   "error.group_page_without_groupname" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Gruppen-Seite zuzugreifen, verwenden Sie bitte das URL-Schema /group/GROUPNAME",
   "error.tag_page_without_tag" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Tag-Seite zuzugreifen, verwenden Sie bitte das URL-Schema /tag/TAG1+TAG+...",
   "error.invalid_openid" : "Die angegebene URL zu Ihren OpenID Provider ist nicht gültig.",
   "error.user_is_group_cannot_be_deleted" : "Dieser Benutzer ist eine Gruppe und kann deshalb leider nicht gelöscht werden.",
   "error.layout.rendering" : "Das angefragte Layout konnte leider nicht erstellt werden (Ausnahme: {0}).",
   "error.field.required" : "Diese Angabe ist notwendig.",
   "error.field.valid.user.email" : "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
   "error.field.valid.user.name" : "Bitte geben Sie einen gültigen Benutzernamen ein.",
   "error.field.valid.user.homepage" : "Bitte geben Sie eine gültige Homepage ein (nur HTTP- und HTTPS-URLs sind erlaubt).",
   "error.field.valid.passwordCheck" : "Die eingegebenen Passwörter stimmen nicht überein.",
   "error.field.valid.captcha" : "Bitte geben Sie die beiden angezeigten Wörter ein.",
   "error.field.valid.url" : "Bitte geben Sie eine gültige URL ein (Anmerkung: URLs beginnen meist mit http://www. ...)",
   "error.field.valid.title" : "Bitte geben Sie einen gültigen Titel ein.",
   "error.field.valid.tags" : "Bitte geben Sie eine Liste von Tags ein.",
   "error.field.valid.tags.comma" : "Komma und Semikolon sind keine gültigen Tag-Trenner.",
   "error.field.valid.url.alreadybookmarked" : "URL bereits gespeichert.",
   "error.field.valid.groups" : "Bitte geben Sie gültige Gruppen an.",
   "error.post.notfound" : "Der Eintrag mit dem angegebenen Hash wurde nicht gefunden.",
   "error.post.update" : "Der Eintrag konnte nicht gespeichert werden.",
   "error.post.redirect" : "Die Weiterleitungs-URL konnte nicht erstellt werden (Ausnahme: {0}). ",
   "error.general.login" : "Sie müssen angemeldet sein.",
   "error.field.valid.ckey" : "Das übergebene Sicherheitsmerkmal ist ungültig.",
   "error.secure.answer" : "Bitte geben Sie \"yes\" ein um Ihren Zugang zu löschen.",
   "error.field.duplicate.user.name" : "Dieser Benutzername existiert bereits. Bitte wählen Sie einen anderen Namen.",
   "error.field.duplicate.user.openid" : "Diese OpenID ist bereits registriert.",
   "error.login.failed" : "Das von Ihnen eingegebene Passwort ist nicht korrekt oder es existiert kein Benutzer mit diesem Namen.",
   "error.login.reminderExpired" : "Das von Ihnen eingegebene Passwort ist nicht mehr gültig.",
   "error.upload.invalid.hash" : "Der Hash der Ressource ist ungültig.",
   "error.upload.failed" : "Der Dateiupload konnte nicht abgeschlossen werden. Es trat folgender Fehler auf: {0}",
   "error.method_not_allowed" : "Aktion nicht erlaubt ",
   "error.permission_denied" : "Zugriff verweigert",
   "error.invalid_parameter" : "Ungültiger Parameter",
   "error.service_unavailable" : "Dienst nicht verfügbar. Bitte versuchen Sie es in {0} Sekunden noch einmal.",
   "error.cookies_required" : "Bitte aktivieren Sie Cookies in Ihrem Webbrowser.",
   "error.captcha" : "Die Überprüfung des Captchas war aufgrund eines Fehlers nicht möglich.",
   "error.passReminder.expired" : "Das temporäre Passwort ist nicht mehr gültig, bitte fordern Sie erneut ein temporäres Passwort an.",
   "error.passReminder.time" : "Sie haben innerhalb der letzten {0} Minuten bereits ein Passwort angefordert. Bitte warten Sie noch {1} Minuten, bis Sie ein neues Passwort anfordern.",
   "typeMismatch.java.net.URL " : " Bitte geben Sie eine gültige URL ein. Typischerweise beginnt eine URL mit \"http://\".",
   "image.button.myProject" : "/resources/image/button_myBibsonomy_de.png",
   "image.button.postBookmark" : "/resources/image/button_postBookmark_de.png",
   "image.button.postPublication" : "/resources/image/button_postPublication_de.png",
   "image.register.success" : "/resources/image/register3.png",
   "actions.admin.group.tagset" : "neue Tagmenge",
   "actions.admin.group.tagsets" : "Tagmengen",
   "actions.admin.group.alltagsets" : "alle Tagmengen",
   "actions.admin.group.administrate" : "Gruppen Administration"
}
