//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.21 at 10:27:22 PM CEST 
//


package org.bibsonomy.rest.renderer.xml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.bibsonomy.rest.renderer.xml.BibsonomyXML;
import org.bibsonomy.rest.renderer.xml.BibtexType;
import org.bibsonomy.rest.renderer.xml.BookmarkType;
import org.bibsonomy.rest.renderer.xml.GroupType;
import org.bibsonomy.rest.renderer.xml.GroupsType;
import org.bibsonomy.rest.renderer.xml.PostType;
import org.bibsonomy.rest.renderer.xml.PostsType;
import org.bibsonomy.rest.renderer.xml.TagsType;
import org.bibsonomy.rest.renderer.xml.UserType;
import org.bibsonomy.rest.renderer.xml.UsersType;


/**
 * <p>Java class for bibsonomyXML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bibsonomyXML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="users" type="{}UsersType"/>
 *           &lt;element name="groups" type="{}GroupsType"/>
 *           &lt;element name="tags" type="{}TagsType"/>
 *           &lt;element name="posts" type="{}PostsType"/>
 *           &lt;element name="user" type="{}UserType"/>
 *           &lt;element name="group" type="{}GroupType"/>
 *           &lt;element name="post" type="{}PostType"/>
 *           &lt;element name="bookmark" type="{}BookmarkType"/>
 *           &lt;element name="bibtex" type="{}BibtexType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "bibsonomyXML", propOrder = {
    "users",
    "groups",
    "tags",
    "posts",
    "user",
    "group",
    "post",
    "bookmark",
    "bibtex"
})
public class BibsonomyXML {

    protected UsersType users;
    protected GroupsType groups;
    protected TagsType tags;
    protected PostsType posts;
    protected UserType user;
    protected GroupType group;
    protected PostType post;
    protected BookmarkType bookmark;
    protected BibtexType bibtex;

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersType }
     *     
     */
    public UsersType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersType }
     *     
     */
    public void setUsers(UsersType value) {
        this.users = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link GroupsType }
     *     
     */
    public GroupsType getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupsType }
     *     
     */
    public void setGroups(GroupsType value) {
        this.groups = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TagsType }
     *     
     */
    public TagsType getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagsType }
     *     
     */
    public void setTags(TagsType value) {
        this.tags = value;
    }

    /**
     * Gets the value of the posts property.
     * 
     * @return
     *     possible object is
     *     {@link PostsType }
     *     
     */
    public PostsType getPosts() {
        return posts;
    }

    /**
     * Sets the value of the posts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostsType }
     *     
     */
    public void setPosts(PostsType value) {
        this.posts = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link GroupType }
     *     
     */
    public GroupType getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupType }
     *     
     */
    public void setGroup(GroupType value) {
        this.group = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link PostType }
     *     
     */
    public PostType getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostType }
     *     
     */
    public void setPost(PostType value) {
        this.post = value;
    }

    /**
     * Gets the value of the bookmark property.
     * 
     * @return
     *     possible object is
     *     {@link BookmarkType }
     *     
     */
    public BookmarkType getBookmark() {
        return bookmark;
    }

    /**
     * Sets the value of the bookmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookmarkType }
     *     
     */
    public void setBookmark(BookmarkType value) {
        this.bookmark = value;
    }

    /**
     * Gets the value of the bibtex property.
     * 
     * @return
     *     possible object is
     *     {@link BibtexType }
     *     
     */
    public BibtexType getBibtex() {
        return bibtex;
    }

    /**
     * Sets the value of the bibtex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibtexType }
     *     
     */
    public void setBibtex(BibtexType value) {
        this.bibtex = value;
    }

}
