//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.19 at 09:00:27 PM CEST 
//


package org.bibsonomy.rest.renderer.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.bibsonomy.rest.renderer.xml.BibsonomyXML;
import org.bibsonomy.rest.renderer.xml.BibtexType;
import org.bibsonomy.rest.renderer.xml.BookmarkType;
import org.bibsonomy.rest.renderer.xml.GroupType;
import org.bibsonomy.rest.renderer.xml.GroupsType;
import org.bibsonomy.rest.renderer.xml.ObjectFactory;
import org.bibsonomy.rest.renderer.xml.PostType;
import org.bibsonomy.rest.renderer.xml.PostsType;
import org.bibsonomy.rest.renderer.xml.TagType;
import org.bibsonomy.rest.renderer.xml.TagsType;
import org.bibsonomy.rest.renderer.xml.UserType;
import org.bibsonomy.rest.renderer.xml.UsersType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bibsonomy.rest.renderer.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BibsonomyXMLInterchangeDocument_QNAME = new QName("", "bibsonomyXMLInterchangeDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bibsonomy.rest.renderer.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BibtexType }
     * 
     */
    public BibtexType createBibtexType() {
        return new BibtexType();
    }

    /**
     * Create an instance of {@link BookmarkType }
     * 
     */
    public BookmarkType createBookmarkType() {
        return new BookmarkType();
    }

    /**
     * Create an instance of {@link BibsonomyXML }
     * 
     */
    public BibsonomyXML createBibsonomyXML() {
        return new BibsonomyXML();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     */
    public TagsType createTagsType() {
        return new TagsType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link UsersType }
     * 
     */
    public UsersType createUsersType() {
        return new UsersType();
    }

    /**
     * Create an instance of {@link PostType }
     * 
     */
    public PostType createPostType() {
        return new PostType();
    }

    /**
     * Create an instance of {@link PostsType }
     * 
     */
    public PostsType createPostsType() {
        return new PostsType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link GroupsType }
     * 
     */
    public GroupsType createGroupsType() {
        return new GroupsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BibsonomyXML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bibsonomyXMLInterchangeDocument")
    public JAXBElement<BibsonomyXML> createBibsonomyXMLInterchangeDocument(BibsonomyXML value) {
        return new JAXBElement<BibsonomyXML>(_BibsonomyXMLInterchangeDocument_QNAME, BibsonomyXML.class, null, value);
    }

}
