apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibsonomy-rest-api-v2
spec:
  template:
    spec:
      containers:
        - name: rest-api
          env:
            - name: BIBSONOMY_CORS_ALLOWED_ORIGINS
              value: PREVIEW_WEB_ORIGIN
