ALTER TABLE `person` ADD `college` VARCHAR(128) DEFAULT NULL AFTER `orcid`;
ALTER TABLE `person` ADD `email` VARCHAR(255) DEFAULT NULL AFTER `college`;
ALTER TABLE `person` ADD `homepage` VARCHAR(255) DEFAULT NULL AFTER `email`;