ALTER TABLE `user` ADD COLUMN `favourite_layouts` LONGTEXT NULL AFTER `reg_log`;
ALTER TABLE `pendingUser` ADD COLUMN `favourite_layouts` LONGTEXT NULL AFTER `reg_log`;

UPDATE `user` SET `favourite_layouts`='JABREF/APA_HTML,SIMPLE/BIBTEX,JABREF/CHICAGO,JABREF/DIN1505,SIMPLE/ENDNOTE,JABREF/HARVARDHTML,JABREF/MSOFFICEXML';
UPDATE `pendingUser` SET `favourite_layouts`='JABREF/APA_HTML,SIMPLE/BIBTEX,JABREF/CHICAGO,JABREF/DIN1505,SIMPLE/ENDNOTE,JABREF/HARVARDHTML,JABREF/MSOFFICEXML';