package org.bibsonomy.model.enums;

/**
 * source of a layout
 * supported sources have to be entered here, else they won't be accepted at all
 * @author jp
 */
public enum FavouriteLayoutSource {
	/** generated by java code */
	SIMPLE,
	/** generated by JabRef */
	JABREF,
	/** generated by CSL */
	CSL;
}
