var LocalizedStrings = { 
   "system.desc" : "Lesezeichen und Referenzen teilen - in blau!",
   "system.about" : "Mit {0} lassen sich einfach und komfortabel Lesezeichen und Publikationen online verwalten und teilen.",
   "system.contact" : "Kontakt:",
   "feeds.bookmark" : "Bookmark RSS feed f&uuml;r",
   "feeds.publication" : "Publication RSS feed f&uuml;r",
   "feeds.burst" : "Burst RSS feed f&uuml;r",
   "navi.tags" : "Tags",
   "navi.groups" : "Gruppen",
   "navi.relations" : "Relationen",
   "navi.popular" : "Beliebt",
   "navi.relations.cap" : "Relationen",
   "navi.my" : "mein",
   "navi.my.plural" : "meine",
   "navi.friends" : "Freunde",
   "navi.friends.cap" : "Freunde",
   "navi.search.cap" : "Suche",
   "navi.pdfs" : "PDFs",
   "navi.duplicates.cap" : "Duplikate",
   "navi.bibtex.cap" : "BibTeX",
   "navi.postBookmark" : "Lesezeichen eintragen",
   "navi.postPublication" : "Publikation eintragen",
   "navi.loggedInAs" : "angemeldet als",
   "navi.help" : "Hilfe",
   "navi.blog" : "Weblog",
   "navi.about" : "&Uuml;ber uns",
   "navi.pickedIn" : "hinzugef&uuml;gt zur",
   "navi.basket" : "Ablage",
   "navi.editTags" : "Tags bearbeiten",
   "navi.friends" : "Freunde",
   "navi.settings" : "Einstellungen",
   "navi.logout" : "Abmelden",
   "navi.login" : "Anmelden",
   "navi.register" : "Registrieren",
   "navi.username" : "Benutzername",
   "navi.password" : "Passwort",
   "navi.tag" : "Tag",
   "navi.user" : "Benutzer",
   "navi.group" : "Gruppe",
   "navi.author" : "Autor",
   "navi.concept" : "Konzept",
   "navi.bibtexKey" : "BibTeX key",
   "navi.search" : "Suche",
   "navi.all" : "alles",
   "navi.join" : "der Gruppe {0} beitreten",
   "navi.search.hint" : "<hier Volltext-Suche eingeben>",
   "navi.tag.hint" : "<Tag(s) eingeben>",
   "navi.user.hint" : "<Benutzername eingeben>",
   "navi.group.hint" : "<Gruppen eingeben>",
   "navi.author.hint" : "<Autoren eingeben>",
   "navi.concept.hint" : "<Konzept-Tags eingeben>",
   "navi.bibtexkey.hint" : "<BibTeX-key eingeben>",
   "bibtex.actions.pick" : "merken",
   "bibtex.actions.pick.title" : "diese Publikation zur Ablage hinzuf&uuml;gen",
   "bibtex.actions.unpick" : "entfernen",
   "bibtex.actions.unpick.title" : "diese Publikation aus der Ablage entfernen",
   "bibtex.actions.copy" : "kopieren",
   "bibtex.actions.copy.title" : "diese Publikation in die eigene Sammlung kopieren",
   "bibtex.actions.editTags" : "taggen",
   "bibtex.actions.editTags.title" : "die Tags dieser Publikation bearbeiten",
   "bibtex.actions.edit" : "bearbeiten",
   "bibtex.actions.edit.title" : "diese Publikation bearbeiten",
   "bibtex.actions.delete" : "l&ouml;schen",
   "bibtex.actions.delete.title" : "diese Publikation aus der eigenen Sammlung l&ouml;schen",
   "bibtex.actions.url" : "URL",
   "bibtex.actions.url.title" : "diese Publikation enth&auml;lt eine URL, die hier verlinkt ist",
   "bibtex.actions.bibtex" : "BibTeX",
   "bibtex.actions.bibtex.title" : "diese Publikation im BibTeX-Format anzeigen",
   "bibtex.actions.openurl" : "openURL",
   "bibtex.actions.openurl.title" : "eine Anfrage an den openURL-Server mit dem Metadaten dieser Publikation senden ",
   "bibtex.edition" : "Edition",
   "bibtex.pages" : "Seite",
   "bibtex.volume" : "Volume",
   "bibtex.volumeOf" : "von",
   "bookmark.actions.edit" : "bearbeiten",
   "bookmark.actions.edit.title" : "dieses Lesezeichen bearbeiten",
   "bookmark.actions.editTags" : "taggen",
   "bookmark.actions.editTags.title" : "die Tags dieses Lesezeichens bearbeiten",
   "bookmark.actions.delete" : "l&ouml;schen",
   "bookmark.actions.delete.title" : "dieses Lesezeichen aus der Sammlung l&ouml;schen",
   "bookmark.actions.copy" : "kopieren",
   "bookmark.actions.delete.title" : "dieses Lesezeichen in die eigene Sammlung kopieren",
   "list.total" : "total",
   "meta.lang" : "de",
   "meta.author" : "Fachgebiet Wissensverarbeitung, Universität Kassel",
   "meta.copyright" : "Fachgebiet Wissensverarbeitung, Universität Kassel",
   "meta.keywords" : "BibTeX, Bookmarks, Folksonomy, Tagging, Wissensverarbeitung, Wissensmanagement, Data Mining, Informatik, Universität Kassel",
   "meta.description" : "Webapplikation des Fachgebiets Wissensverarbeitung, Universität Kassel",
   "error" : "Fehler",
   "publications" : "Publikationen",
   "friends" : "Freunde",
   "bookmarks" : "Lesezeichen",
   "posts" : "Eintr&auml;ge",
   "post" : "Eintrag",
   "tags" : "Tags",
   "busytags" : "beliebte Tags",
   "tag" : "Tag",
   "relatedtags" : "Verwandte Tags",
   "and" : "und",
   "members" : "Mitglieder",
   "previous" : "&lt;",
   "first" : "&lt;&lt;",
   "goto.previous" : "zur vorherigen Seite wechseln",
   "goto.first" : "zur ersten Seite wechseln",
   "next" : "&gt;",
   "last" : "&gt;&gt;",
   "goto.next" : "zur n&auml;chsten Seite wechseln",
   "goto.last" : "zur letzten Seite wechseln",
   "tagged.to" : "als",
   "tagged.by" : "von",
   "other.person" : "anderen Person",
   "other.people" : "anderen Personen",
   "tagged.time.on" : "am",
   "edit" : "bearbeiten",
   "group.as" : "zur Gruppe",
   "page.edit.tags" : "die Tags der eigenen Lesezeichen auf dieser Seite bearbeiten",
   "pick" : "merken",
   "page.pick.publications" : "alle Publikationen dieser Seite in die Ablage legen",
   "unpick" : "vergessen",
   "page.unpick.publications" : "alle Publikationen dieser Seite aus der Ablage entfernen",
   "list.show" : "Zeige",
   "list.entriesPerPage" : "pro Seite",
   "tagbox.alph" : "alpha",
   "tagbox.freq" : "freq",
   "tagbox.cloud" : "Wolke",
   "tagbox.list" : "Liste",
   "tagbox.minfreq" : "minfreq",
   "tagrelations" : "Relationen",
   "tagrelations.title" : "Alle Relationen dieses Benutzers anzeigen",
   "tagrelations.showAll" : "alle anzeigen",
   "tagrelations.showAll.title" : "alle Relationen anzeigen",
   "tagrelations.hideAll" : "alle verbergen",
   "tagrelations.hideAll.title" : "alle Relationen verbergen",
   "tagrelations.hide" : "&darr;",
   "tagrelations.hide.title" : "Relation verbergen",
   "tagrelations.showPostsForConcept.title" : "Alle Eintr&auml;ge anzeigen, die mit {0} oder dessen Subtag bezeichnet sind",
   "related.concept" : "als Konzept",
   "related.tag" : "als Tag",
   "error.user_page_without_username" : "Diese Seite existiert leider nicht auf unserem Server. Um auf eine Benutzerseite zuzugreifen, verwenden Sie bitte das URL-Schema /user/USERNAME."
}
