var LocalizedStrings = { 
   "system.desc" : "Lesezeichen und Referenzen teilen - in blau!",
   "system.name" : "BibSonomy",
   "system.about" : "Mit BibSonomy lassen sich einfach und komfortabel Lesezeichen und Publikationen online verwalten und teilen.",
   "system.contact" : "Kontakt:",
   "system.contact.email_username" : "webmaster",
   "system.contact.email_hostname" : "bibsonomy.org",
   "system.path.delim" : "::",
   "feeds.bookmark" : "Bookmark RSS feed f&uuml;r",
   "feeds.publication" : "Publication RSS feed f&uuml;r",
   "feeds.burst" : "Burst RSS feed f&uuml;r",
   "navi.tags" : "Tags",
   "navi.groups" : "Gruppen",
   "navi.relations" : "Relationen",
   "navi.popular" : "Beliebt",
   "navi.relations.cap" : "Relationen",
   "navi.my" : "mein",
   "navi.my.plural" : "meine",
   "navi.friends" : "Freunde",
   "navi.friends.cap" : "Freunde",
   "navi.search.cap" : "Suche",
   "navi.pdfs" : "PDFs",
   "navi.duplicates.cap" : "Duplikate",
   "navi.bibtex.cap" : "BibTeX",
   "navi.postBookmark" : "Lesezeichen eintragen",
   "navi.postPublication" : "Publikation eintragen",
   "navi.loggedInAs" : "eingeloggt als",
   "navi.help" : "Hilfe",
   "navi.blog" : "Weblog",
   "navi.about" : "&Uuml;ber uns",
   "navi.pickedIn" : "hinzugef&uuml;gt zur",
   "navi.basket" : "Ablage",
   "navi.editTags" : "Tags bearbeiten",
   "navi.friends" : "Freunde",
   "navi.settings" : "Einstellungen",
   "navi.logout" : "Abmelden",
   "navi.login" : "Anmelden",
   "navi.register" : "Registrieren",
   "navi.username" : "Benutzername",
   "navi.password" : "Passwort",
   "navi.tag" : "Tag",
   "navi.user" : "Benutzer",
   "navi.group" : "Gruppe",
   "navi.author" : "Autor",
   "navi.concept" : "Konzept",
   "navi.bibtexKey" : "BibTeX key",
   "navi.search" : "Suche",
   "navi.all" : "alles",
   "navi.search.hint" : "<hier Volltext-Suche eingeben>",
   "navi.tag.hint" : "<Tag(s) eingeben>",
   "navi.user.hint" : "<Benutzername eingeben>",
   "navi.group.hint" : "<Gruppen eingeben>",
   "navi.author.hint" : "<Autoren eingeben>",
   "navi.concept.hint" : "<Konzept-Tags eingeben>",
   "navi.bibtexkey.hint" : "<BibTeX-key eingeben>",
   "bibtex.actions.pick" : "merken",
   "bibtex.actions.pick.title" : "diese Publikation zur Ablage hinzuf&uuml;gen",
   "bibtex.actions.unpick" : "entfernen",
   "bibtex.actions.unpick.title" : "diese Publikation aus der Ablage entfernen",
   "bibtex.actions.copy" : "kopieren",
   "bibtex.actions.copy.title" : "diese Publikation in die eigene Sammlung kopieren",
   "bibtex.actions.editTags" : "taggen",
   "bibtex.actions.editTags.title" : "die Tags dieser Publikation bearbeiten",
   "bibtex.actions.edit" : "bearbeiten",
   "bibtex.actions.edit.title" : "diese Publikation bearbeiten",
   "bibtex.actions.delete" : "l&ouml;schen",
   "bibtex.actions.delete.title" : "diese Publikation aus der eigenen Sammlung l&ouml;schen",
   "bibtex.actions.url" : "URL",
   "bibtex.actions.url.title" : "diese Publikation enth&auml;lt eine URL, die hier verlinkt ist",
   "bibtex.actions.bibtex" : "BibTeX",
   "bibtex.actions.bibtex.title" : "diese Publikation im BibTeX-Format anzeigen",
   "bibtex.actions.openurl" : "openURL",
   "bibtex.actions.openurl.title" : "eine Anfrage an den openURL-Server mit dem Metadaten dieser Publikation senden ",
   "bibtex.edition" : "Edition",
   "bibtex.pages" : "Seite",
   "bibtex.volume" : "Volume",
   "bibtex.volumeOf" : "von",
   "bookmark.actions.editTags" : "taggen",
   "bookmark.actions.editTags.title" : "die Tags dieses Lesezeichens bearbeiten",
   "bookmark.actions.delete" : "l&ouml;schen",
   "bookmark.actions.delete.title" : "dieses Lesezeichen aus der Sammlung l&ouml;schen",
   "bookmark.actions.copy" : "kopieren",
   "bookmark.actions.delete.title" : "dieses Lesezeichen in die eigene Sammlung kopieren",
   "list.total" : "total",
   "meta.lang" : "de",
   "meta.author" : "Fachgebiet Wissensverarbeitung, Universität Kassel",
   "meta.copyright" : "Fachgebiet Wissensverarbeitung, Universität Kassel",
   "meta.email" : "webmaster@bibsonomy.org",
   "meta.keywords" : "BibTeX, Bookmarks, Folksonomy, Tagging, Wissensverarbeitung, Wissensmanagement, Data Mining, Informatik, Universität Kassel",
   "meta.description" : "Webapplikation des Fachgebiets Wissensverarbeitung, Universität Kassel",
   "error" : "Fehler",
   "publications" : "Publikationen",
   "friends" : "Freunde",
   "bookmarks" : "Lesezeichen",
   "posts" : "Eintr&auml;ge",
   "post" : "Eintrag",
   "tags" : "Tags",
   "tag" : "Tag",
   "and" : "und",
   "previous" : "<",
   "first" : "<<",
   "goto.previous" : "zur vorherigen Seite wechseln",
   "next" : ">",
   "last" : ">>",
   "goto.next" : "zur n&auml;chsten Seite wechseln",
   "tagged.to" : "als",
   "tagged.by" : "von",
   "other.person" : "anderen Person",
   "other.people" : "anderen Personen",
   "tagged.time.on" : "um",
   "edit" : "bearbeiten",
   "group.as" : "zur Gruppe",
   "page.edit.tags" : "die Tags der eigenen Lesezeichen auf dieser Seite bearbeiten",
   "tagbox.alph" : "alpha",
   "tagbox.freq" : "freq",
   "tagbox.cloud" : "Wolke",
   "tagbox.list" : "Liste",
   "tagbox.minfreq" : "minfreq",

}
