var LocalizedStrings = { 
   "Show" : "Show",
   "actions.admin.group.administrate" : "Group Administration",
   "actions.admin.group.alltagsets" : "all tagsets",
   "actions.admin.group.tagset" : "new tagset",
   "actions.admin.group.tagsets" : "tagsets",
   "additional" : "additional",
   "and" : "and",
   "available" : "available",
   "basket.groupmetadata" : "edit meta data for group",
   "basket.info" : "Here you can manage publication posts you picked with the \"pick\" button. For details see <a href",
   "basket.removeAll" : "remove all from basket",
   "basket.removeAllVerbose" : "remove all publications from the basket",
   "batchedit.allTags" : "These tags will be added to <strong>ALL</strong> posts shown on this page!",
   "batchedit.button.update" : "update",
   "batchedit.deleteAll" : "delete all posts",
   "batchedit.deleteAll.confirm" : "Do you really want to mark all posts to be deleted?",
   "batchedit.deletePost" : "delete post",
   "batchedit.deletePostQ" : "Delete post?",
   "batchedit.disregardedPosts" : "Disregarded posts",
   "batchedit.disregardedPosts.info" : "The following posts are not your own and therefore you can not change their tags.",
   "batchedit.info" : "Here you can edit your posts",
   "batchedit.yourPosts" : "Your posts",
   "batchedit.yourTags" : "Your tags",
   "bibtex.abstract" : "abstract",
   "bibtex.abstract.cap" : "Abstract",
   "bibtex.actions.additional_url.add" : "add",
   "bibtex.actions.additional_url.add.title" : "add another additional URL",
   "bibtex.actions.additional_url.delete" : "delete",
   "bibtex.actions.additional_url.delete.title" : "delete this additional URL",
   "bibtex.actions.bibtex" : "BibTeX",
   "bibtex.actions.bibtex.title" : "show this publication in BibTeX format",
   "bibtex.actions.copy" : "copy",
   "bibtex.actions.copy.title" : "copy this publication to your repository",
   "bibtex.actions.delete" : "delete",
   "bibtex.actions.delete.confirm" : "Do you really want to delete this publication?",
   "bibtex.actions.delete.title" : "delete this publication from your repository",
   "bibtex.actions.edit" : "edit",
   "bibtex.actions.edit.title" : "edit this publication",
   "bibtex.actions.editTags" : "edit",
   "bibtex.actions.editTags.title" : "edit the tags of this publication",
   "bibtex.actions.openurl" : "openURL",
   "bibtex.actions.openurl.title" : "query your openURL-Server with the metadata of this publication",
   "bibtex.actions.pick" : "pick",
   "bibtex.actions.pick.title" : "add this publication to your basket",
   "bibtex.actions.private_document.delete" : "delete",
   "bibtex.actions.private_document.description" : "Your private copy of this document",
   "bibtex.actions.private_document.download" : "download",
   "bibtex.actions.private_document.upload" : "upload",
   "bibtex.actions.private_document.upload.title" : "Upload your private copy (PDF, PS, ...) of this publication.",
   "bibtex.actions.tags.update" : "Update tags",
   "bibtex.actions.unpick" : "unpick",
   "bibtex.actions.unpick.title" : "remove this publication from your basket",
   "bibtex.actions.url" : "URL",
   "bibtex.actions.url.title" : "this publication contains a URL which is linked here",
   "bibtex.additional_urls" : "Additional URLs",
   "bibtex.all_exports" : "all formats",
   "bibtex.all_exports.title" : "show all export formats (including RSS, CVS, ...)",
   "bibtex.citation_format" : "Citation format",
   "bibtex.details.owner" : "entry of",
   "bibtex.edition" : "edition",
   "bibtex.editors.abbr" : "Eds.",
   "bibtex.pages" : "page",
   "bibtex.private_note" : "Private note",
   "bibtex.resources" : "Resources (URL, PDF, PS...)",
   "bibtex.upload.file.back" : "Back",
   "bibtex.upload.file.button" : "add",
   "bibtex.upload.file.hash" : "The MD5 hash value of the file contents",
   "bibtex.upload.file.helptext" : "Here you can add a document to your post. Just choose the file and click on the \"add\" button.",
   "bibtex.upload.file.label" : "Your private copy of the document",
   "bibtex.upload.file.page" : "upload document",
   "bibtex.upload.file.success" : "The file has been uploaded successfully.",
   "bibtex.url" : "URL",
   "bibtex.volume" : "volume",
   "bibtex.volumeOf" : "of",
   "bookmark.actions.copy" : "copy",
   "bookmark.actions.copy.title" : "copy this bookmark to your repository",
   "bookmark.actions.delete" : "delete",
   "bookmark.actions.delete.title" : "delete this bookmark from your repository",
   "bookmark.actions.edit" : "edit",
   "bookmark.actions.edit.title" : "edit this bookmark",
   "bookmark.actions.editTags" : "edit",
   "bookmark.actions.editTags.title" : "edit the tags of this bookmark",
   "bookmarks" : "bookmarks",
   "busytags" : "busy tags",
   "buttons.bookmarklet" : "Bookmarklet buttons for {0}",
   "buttons.javascript" : "You need JavaScript enabled.",
   "buttons.javascript_appear" : "will appear as",
   "buttons.javascript_code" : "JavaScript Code",
   "buttons.javascript_code_image" : "JavaScript Code with Image",
   "buttons.javascript_snippets" : "Javascript Code Snippets",
   "buttons.javascript_snippets_text" : "The code below is meant to be incorporated into existing websites in order to ease posting bookmarks and publications to {0}. It will display a link which leads directly to the appropriate (bookmark or publication) posting page in {0}.",
   "buttons.myProject.title" : "Drag this button to your browsers personal link toolbar.",
   "buttons.mybibsonomy" : "my{0}",
   "buttons.mybibsonomy_part_five" : ", which you can also reach from every page with the",
   "buttons.mybibsonomy_part_four" : "personal home page",
   "buttons.mybibsonomy_part_one" : "By dragging the",
   "buttons.mybibsonomy_part_six" : "link in the upper navigation menu.",
   "buttons.mybibsonomy_part_three" : "If you have read enough of the <a href",
   "buttons.mybibsonomy_part_two" : "button to your links toolbar you can access {0} by just one click in your browser.",
   "buttons.select_code" : "select code",
   "buttons.shortcut_bibtex" : "Shortcut for posting publication references",
   "buttons.shortcut_bibtex_end" : "Then you just need to select (highlight) a publicatio entry you find on a web page and after clicking on the button the entry will be stored in {0}.",
   "buttons.shortcut_bookmarks" : "Shortcut for posting bookmarks",
   "buttons.shortcut_bookmarks_end" : "Whenever you are on an interesting webpage, you just click on this button. You are asked to type in some tags, and the bookmark is automatically added to your library. Then you can continue your navigation.",
   "buttons.shortcut_login_one" : "If you were",
   "buttons.shortcut_login_three" : ", you could find here a button which you can drag to the links toolbar of your browser.",
   "buttons.shortcut_login_two" : "logged in",
   "buttons.shortcut_one" : "Drag the",
   "buttons.shortcut_three" : "button. (If you use Internet Explorer you have to right-click on the button and select \"add to favorites\".)",
   "buttons.shortcut_two" : "button to the links toolbar of your browser once. If you are a friend of popup windows, you can also use the",
   "by" : "by",
   "captcha" : "captcha",
   "change" : "change",
   "create" : "create",
   "days" : "days",
   "description" : "description",
   "edittags.example.partFour" : "This would be done in all posts which contain the tags",
   "edittags.example.partOne" : "This example shows the substitution of the tags",
   "edittags.example.partThree" : "by the tags",
   "edittags.example.partand" : "and",
   "edittags.main.Header" : "rename/replace all your tags",
   "edittags.main.NoteOne" : "NOTE",
   "edittags.main.NoteTwo" : "This works only, when exactly one tag is substituted by another.",
   "edittags.main.deleteRelationsOne" : "delete relations",
   "edittags.main.deleteRelationsTwo" : "relations to delete",
   "edittags.main.insertRelationsOne" : "insert relations",
   "edittags.main.insertRelationsTwo" : "relations to insert",
   "edittags.main.newtags" : "new tag(s)",
   "edittags.main.replace" : "tag(s) to replace",
   "edittags.main.textOne" : "In all posts which contain all of the tags in the first box these tags will be substituted by the tags in the second box.",
   "edittags.main.updaterelations" : "also update relations",
   "edittags.update.partOne" : "update successful",
   "edittags.update.relations" : "relation(s)",
   "edittags.update.resources" : "resource(s)",
   "edittags.update.updated" : "updated",
   "error" : "error",
   "error.author_page_without_authorname" : "Sorry, this page does not exist on our server. I your want to access an author page, please specify an author name like /author/AUTHORNAME",
   "error.bibtex_no_hash" : "Sorry, this page does not exist on our server. If you want to access a bibtex page, please specify a bibtexkey like /bibtex/HASH.",
   "error.bibtexkey_no_key" : "Sorry, this page does not exist on our server. If you want to access a bibtexkey page, please specify a bibtexkey like /bibtexkey/KEY.",
   "error.captcha" : "Could not validate captcha due to a remote server error.",
   "error.concept_page_without_conceptname" : "Sorry, this page does not exist on our server. I your want to access a concept page, please specify a concept name like /concept/tag/CONCEPT or /concept/user/USERNAME/CONCEPTNAME",
   "error.cookies_required" : "Please enable cookies in your browser.",
   "error.document_not_found" : "Sorry, the requested document could not be found.",
   "error.field.duplicate.user.name" : "This user name already exists. Please choose another name.",
   "error.field.duplicate.user.openid" : "This OpenID already exists.",
   "error.field.required" : "This field is required.",
   "error.field.valid.authorOrEditor" : "Please enter authors or editors for this publication.",
   "error.field.valid.bibtexKey" : "Please enter a valid key for your entry. The key might not contain whitespace.",
   "error.field.valid.captcha" : "Please enter the words shown.",
   "error.field.valid.ckey" : "The provided security token is invalid.",
   "error.field.valid.entrytype" : "Please choose an entrytype.",
   "error.field.valid.groups" : "Please enter valid groups.",
   "error.field.valid.misc" : "Please enter valid BibTeX fields.",
   "error.field.valid.passwordCheck" : "The passwords you entered do not match.",
   "error.field.valid.tags" : "Please enter valid tags.",
   "error.field.valid.tags.comma" : "Comma and semicolon are not valid tag separators.",
   "error.field.valid.title" : "Please enter a title.",
   "error.field.valid.url" : "Please enter a valid URL (typically, URLs start with http://www. ...).",
   "error.field.valid.url.alreadybookmarked" : "You have already bookmarked this URL.",
   "error.field.valid.user.email" : "Please enter a valid email address.",
   "error.field.valid.user.homepage" : "Please enter a valid homepage (only http and https URLs are allowed).",
   "error.field.valid.user.name" : "Please enter a valid user name.",
   "error.field.valid.year" : "Please enter a year.",
   "error.friend_page_without_friendname" : "Sorry, this page does not exist on our server. If you want to access a friend page, please specify a username like /friend/FRIENDNAME.",
   "error.friends_page_not_logged_in" : "In order to access this page, you need to be logged in.",
   "error.furtherInformations" : "For further information read the error-message: {0}",
   "error.general.login" : "You have to be logged in.",
   "error.group_page_without_groupname" : "Sorry, this page does not exist on our server. I your want to access a group page, please specify a group name like /group/GROUPNAME",
   "error.import.failed" : "Import failed!",
   "error.internal" : "Internal Server Error: {0}",
   "error.invalid_forward_page" : "Invalid forward page",
   "error.invalid_openid" : "Sorry, the url to your OpenID provider is not valid.",
   "error.invalid_parameter" : "invalid parameter",
   "error.layout.rendering" : "Sorry, the requested layout could not be rendered (exception is: {0}).",
   "error.login.failed" : "The password and username you entered do not match or the username is not registered.",
   "error.login.reminderExpired" : "The password you used has expired.",
   "error.method_not_allowed" : "method not allowed",
   "error.order_not_supported" : "The order you requested is not supported by our system. We currently support the orders \"added\", \"popular\" and \"folkrank\".",
   "error.passReminder.expired" : "The temporary password isn't valid anymore, please request a new one.",
   "error.passReminder.time" : "You already requested a password in the last {0} minutes. Please wait {1} minutes before you can request a new password.",
   "error.pdf_only_not_authorized_for_group" : "Sorry, you are not authorized to see the documents for this group.",
   "error.pdf_only_not_authorized_for_user" : "Sorry, you are not authorized to see the documents for this user.",
   "error.permission_denied" : "permission denied",
   "error.post.notfound" : "The post with the given intra hash could not be found.",
   "error.post.redirect" : "Could not encode redirect URL. Exception was: {0}",
   "error.post.update" : "Updating the post failed.",
   "error.relationship_with_dblp" : "Sorry, you cannot create a relationship with the user 'dblp' in our system, because it is a special user.",
   "error.search_more_than_one_group" : "Sorry, you can search only within the entries of ONE group.",
   "error.search_more_than_one_user" : "Sorry, you can search only within the entries of ONE user.",
   "error.search_page_without_search" : "Sorry, this page does not exist on our server. If you want to access a search page, please specify your search like /search/SEARCHTERM.",
   "error.secure.answer" : "Type in \"yes\" to delete your account.",
   "error.service_unavailable" : "Service unavailable. Retry after {0} seconds.",
   "error.settings.tab" : "The choosen TabID is not valid",
   "error.tag_page_without_tag" : "Sorry, this page does not exist on our server. If you want to access a tag page, please specify one or more tags like /tag/TAG1+TAG+...",
   "error.upload.failed" : "The file upload did not finish because of the following exception: {0}",
   "error.upload.invalid.hash" : "The provided resource hash is invalid.",
   "error.url_no_hash" : "Sorry, this page does not exist on our server. If you want to access a viewable page, please specify a bibtexkey like /url/HASH.",
   "error.user_is_group_cannot_be_deleted" : "Sorry, this user is a group and cannot be deleted.",
   "error.user_page_with_wrong_user_similarity" : "Sorry, the user similarity is not supported. Try 'folkrank', 'jaccard' or 'tfidf'.",
   "error.user_page_without_username" : "Sorry, this page does not exist on our server. If you want to access a user page, please specify a username like /user/USERNAME.",
   "error.viewable_page_not_logged_in" : "In order to access this page, you need to be logged in so that we can check whether you are a member of the requested group. In order to see public posts of a given group, use, the URL scheme /group/GROUPNAME.",
   "error.viewable_page_without_group" : "Sorry, this page does not exist on our server. If you want to access a viewable page, please specify a groupname like /viewable/GROUPNAME.",
   "export.bibtex.faq" : "<a href",
   "export.bibtex.record" : "BibTeX record",
   "export.burst.faq" : "This is an <a href",
   "export.custom.faq" : "A custom <a href",
   "export.endnote.record" : "Endnote record",
   "export.format" : "format",
   "export.header" : "Export publications",
   "export.html.faq" : "This gives you a simple <a href",
   "export.info" : "By selecting one of the formats you can export the publications of the page {0} in that format.",
   "export.jabref.explain" : "The export filters marked with a star * are from <a href",
   "export.rss.faq" : "With an appropriate <a href",
   "export.swrc.faq" : "This is an <a href",
   "feeds.bookmark" : "Bookmark RSS feed for",
   "feeds.burst" : "Burst RSS feed for",
   "feeds.publication" : "Publication RSS feed for",
   "feeds.swrc" : "SWRC output for",
   "filter" : "filter",
   "filter.justPdf" : "with documents only",
   "filter.none" : "none",
   "first" : "&lt;&lt;",
   "follow" : "follow",
   "follow.actions.delete.title" : "stop following {0}",
   "follow.addFollower" : "Follow somebody",
   "follow.followerof" : "You're followed by:",
   "follow.info.text1" : "You're not following this user:",
   "follow.info.text2" : "You're following this user:",
   "follow.link.text.follow" : "follow",
   "follow.link.text.followLong" : "Follow this user",
   "follow.link.text.remove" : "remove",
   "follow.link.text.removeLong" : "Stop following this user",
   "follow.offollower" : "You're following:",
   "followersPage.about" : "When you \"follow\" a user, you can keep track of all his interesting posts. <a href",
   "followersPage.all.mostRecent.contentHeading" : "This page shows you the {0} most recent posts which might be interesting for you ({1}).",
   "followersPage.all.recent.contentHeading" : "This page shows you recent posts ({0} to {1}) which might be interesting for ({2}).",
   "followersPage.contentHeading" : "The following bookmark and bibtex posts of user {0} might be interesting for you.",
   "followersPage.entries.ofAllFollowedUsers" : "of all users you are following",
   "followersPage.entries.ofUser" : "of the user {0} whom you are following",
   "for" : "for",
   "form.input.select" : "--please select--",
   "friend" : "friend",
   "friends" : "friends",
   "friends.actions.delete" : "delete",
   "friends.actions.delete.title" : "remove {0} from your friend list",
   "friends.addfriend" : "add a friend",
   "friends.button.add" : "add",
   "friends.friendof" : "you are a friend of",
   "friends.yourfriends" : "your friends are",
   "general" : "general information",
   "goto.first" : "go to the first page",
   "goto.last" : "go to the last page",
   "goto.next" : "go to the next page",
   "goto.previous" : "go to the previous page",
   "group" : "group",
   "group.as" : "as",
   "hide" : "hide",
   "image.button.myProject" : "/resources/image/button_myBibsonomy.png",
   "image.button.postBookmark" : "/resources/image/button_postBookmark.png",
   "image.button.postPublication" : "/resources/image/button_postPublication.png",
   "image.register.success" : "/resources/image/register3.png",
   "import" : "import",
   "import.bundles" : "bundles",
   "import.concepts" : "concepts",
   "import.created" : "created",
   "import.delicious" : "Delicious",
   "import.failed" : "failed",
   "import.firefox" : "Firefox",
   "import.kind" : "Which kind of data do you want to import?",
   "import.newResources" : "successfully created {0} {1}:",
   "import.nonImportedResources" : "There are {0} {1} which could not get imported. Please use the overwrite functionality.",
   "import.overwrite" : "{0} bookmarks overwrite {1} bookmarks",
   "import.results" : "Import Results",
   "import.totalcount" : "Found {0} {1}!",
   "import.updated" : "updated",
   "import.updatedResources" : "successfully updated {0} {1}:",
   "last" : "&gt;&gt;",
   "list.entriesPerPage" : "per page",
   "list.show" : "show",
   "list.total" : "total",
   "login.lostPassword" : "lost password",
   "login.lostPassword_1" : "I've lost my password.",
   "login.lostPassword_2" : "Please send me a new one.",
   "login.notRegistered_1" : "I am not registered, but want to do this",
   "login.notRegistered_2" : "now",
   "login.notice.post.bookmark" : "You tried to save a bookmark from an external web page.",
   "login.notice.post.publication" : "You tried to save a publication reference from an external web page.",
   "login.notice.welcome_1" : "Welcome to",
   "login.notice.welcome_2" : "a system for managing and sharing bookmarks and publication posts.",
   "login.notice.welcome_3" : "To accomplish this, please login or",
   "login.notice.welcome_4" : "create a new account",
   "login.title" : "Login",
   "login.withOpenID" : "Login with OpenID",
   "login.withUsernameAndPassword" : "Login with username and password",
   "mail.registration.body" : "\\nThank you for using {1}\\n\\nyour username is {0}\\nyour {1} home page is {2}user/{0}\\n\\nHave a look at the help page and the FAQ:\\n{2}help\\n{2}help/faq\\n\\nNews regarding {1} can be found in our blog:\\n{3}\\n\\nReplies to this e-mail address are deleted, please send questions to {4}.",
   "mail.registration.subject" : "Your {1} Registration",
   "mail.reminder.body" : "Hello {0}!\\n\\nSomeone has requested a new password for your {1} account.\\nYour old password will be valid until you change it by logging in with the temporary password.\\nThe temporary password is valid for {5} minutes only.\\n\\nTemporary password: {6}\\n\\nUse it to log in at {2}login\\n\\nHave a look at the help page and the FAQ:\\n{2}help\\n{2}help/faq\\n\\nNews regarding {1} can be found in our blog:\\n{3}\\n\\nReplies to this e-mail address are deleted, please send questions to {4}.",
   "mail.reminder.subject" : "Your {1} password request",
   "members" : "members",
   "meta.author" : "Knowledge and Data Engineering Group, University of Kassel, Germany",
   "meta.copyright" : "Knowledge and Data Engineering Group, University of Kassel, Germany",
   "meta.description" : "Webapplication of the Knowledge and Data Engineering Group, University of Kassel, Germany",
   "meta.keywords" : "BibTeX, bookmarks, knowledge discovery, folksonomy, tagging, knowledge management, data mining, computer science, University of Kassel",
   "meta.lang" : "en",
   "more" : "more",
   "mysearch.header" : "Search my{0}",
   "mysearch.option.author" : "authors",
   "mysearch.option.filter" : "filter:",
   "mysearch.option.filter.text" : "<enter title, authors or tags>",
   "mysearch.option.header" : "search options",
   "mysearch.option.result.header" : "search results",
   "mysearch.option.result.lang" : "results",
   "mysearch.option.tag" : "tags",
   "name" : "name",
   "navi.about" : "about",
   "navi.admin" : "admin",
   "navi.admin_nospammer" : "Admin: No Spammer",
   "navi.admin_spammer" : "Admin: Spammer",
   "navi.admin_unsure" : "Admin: Unsure",
   "navi.all" : "all",
   "navi.all.persons" : "all",
   "navi.author" : "author",
   "navi.author.hint" : "<enter author(s) here>",
   "navi.authors" : "authors",
   "navi.basket" : "basket",
   "navi.bibtex.cap" : "BibTeX",
   "navi.bibtexkey" : "BibTeX key",
   "navi.bibtexkey.hint" : "<enter BibTeX key here>",
   "navi.blog" : "blog",
   "navi.buttons" : "buttons",
   "navi.classifier_evaluate" : "Modified BibTex Users",
   "navi.classifier_nospammer" : "Classifier: No Spammer",
   "navi.classifier_nospammer_unsure" : "Classifier: No Spammer (U)",
   "navi.classifier_spammer" : "Classifier: Spammer",
   "navi.classifier_spammer_unsure" : "Classifier: Spammer (U)",
   "navi.concept" : "concept",
   "navi.concept.hint" : "<enter concept tag(s) here>",
   "navi.duplicates.cap" : "Duplicates",
   "navi.editBookmark" : "edit bookmark",
   "navi.editTags" : "edit tags",
   "navi.export" : "export",
   "navi.followedUsers" : "followed Users",
   "navi.followedUsers.my" : "followed Users",
   "navi.followees" : "followed users",
   "navi.followers" : "followers",
   "navi.friend" : "friend",
   "navi.friends" : "friends",
   "navi.friends.cap" : "Friends",
   "navi.gender" : "gender",
   "navi.go" : "go",
   "navi.group" : "group",
   "navi.group.cap" : "Group",
   "navi.group.hint" : "<enter group here>",
   "navi.groups" : "groups",
   "navi.groups.cap" : "Groups",
   "navi.help" : "help",
   "navi.helpUrl" : "/help",
   "navi.imports" : "imports",
   "navi.join" : "join group {0}",
   "navi.loggedInAs" : "logged in as",
   "navi.login" : "login",
   "navi.logout" : "logout",
   "navi.my" : "my",
   "navi.my.plural" : "my",
   "navi.myprofile" : "my profile",
   "navi.mysearch" : "mySearch",
   "navi.newregistrations" : "New registrations",
   "navi.passChangeOnRemind" : "password change",
   "navi.passReminder" : "password reminder",
   "navi.passReminder.button" : "send",
   "navi.password" : "password",
   "navi.pdfs" : "PDFs",
   "navi.pickedIn" : "picked in",
   "navi.place" : "place",
   "navi.popular" : "popular",
   "navi.postBookmark" : "post bookmark",
   "navi.postPublication" : "post publication",
   "navi.purposes" : "purposes",
   "navi.purposetags" : "purpose tags",
   "navi.register" : "register",
   "navi.relations" : "relations",
   "navi.relations.cap" : "Relations",
   "navi.relevantFor" : "relevantFor",
   "navi.search" : "search",
   "navi.search.cap" : "Search",
   "navi.search.hint" : "<fulltext search here>",
   "navi.settings" : "settings",
   "navi.tag" : "tag",
   "navi.tag.hint" : "<enter tag(s) here>",
   "navi.tags" : "tags",
   "navi.user" : "user",
   "navi.user.hint" : "<enter user here>",
   "navi.username" : "username",
   "navi.viewable" : "viewable",
   "next" : "&gt;",
   "no" : "no",
   "older" : "older",
   "personalize" : "personalize",
   "personalized" : "personalized",
   "plain" : "plain",
   "post" : "post",
   "post.Bookmark.edit.existent" : "Note: You are editing an existing post.",
   "post.meta.add" : "add",
   "post.meta.asGroup" : "as",
   "post.meta.copy_this_post" : "Copy this post.",
   "post.meta.delete.confirm" : "Do you really want to delete this post?",
   "post.meta.documents" : "All of your publication posts which have a document (PDF, PS or DJVU) attached",
   "post.meta.duplicates" : "All of your publication posts which you have at least twice",
   "post.meta.edit" : "edit",
   "post.meta.edit.title" : "edit the details of all your posts from this list",
   "post.meta.flag_as_spam" : "spam",
   "post.meta.flag_as_spam.title" : "Mark this post as spam",
   "post.meta.kill_spammer" : "KillSpammer!",
   "post.meta.otherPeople" : "other people",
   "post.meta.otherPerson" : "other person",
   "post.meta.own_post" : "You already own this post.",
   "post.meta.pick" : "pick",
   "post.meta.pick.title" : "add all publication posts from this page to your basket",
   "post.meta.recommended" : "Recommended",
   "post.meta.save_as_bookmark" : "Post as bookmark",
   "post.meta.save_as_publication" : "Post as publication",
   "post.meta.taggedBy" : "by",
   "post.meta.taggedOn" : "on",
   "post.meta.taggedTo" : "to",
   "post.meta.unflag_as_spam" : "no spam",
   "post.meta.unflag_as_spam.title" : "Mark this post as no spam",
   "post.meta.unpick" : "unpick",
   "post.meta.unpick.title" : "remove all publication posts from this page from your basket",
   "post.resource.about" : "about",
   "post.resource.aboutrelevantfor" : "add some tags which describe the relevance of your post for some groups",
   "post.resource.bookmark_a_publication" : "The page you are trying to bookmark contains the following publication reference",
   "post.resource.comment" : "comment",
   "post.resource.copytags" : "tags of copied post",
   "post.resource.description" : "description",
   "post.resource.description.cap" : "Description",
   "post.resource.editBookmark" : "Feel free to edit your bookmark",
   "post.resource.go" : "Go!",
   "post.resource.hint" : "Posting could be so easy: just <strong>drag and drop</strong> our <a href",
   "post.resource.notagset" : "Currently there are no tagsets available for this group.",
   "post.resource.other" : "other",
   "post.resource.private" : "private",
   "post.resource.public" : "public",
   "post.resource.purpose" : "purpose",
   "post.resource.purposetext" : "helps me to",
   "post.resource.recommendation" : "recommendation",
   "post.resource.relevant" : "If your post is interesting for one or more groups, you can mark your post \"relevant\" for these groups.",
   "post.resource.relevantfor" : "relevant for",
   "post.resource.reloadRecommendation" : "reload recommended tags",
   "post.resource.requiredfield" : "required",
   "post.resource.spaceseparated" : "space separated",
   "post.resource.suggested" : "auto-complete:",
   "post.resource.tags" : "tags",
   "post.resource.tags.cap" : "Tags",
   "post.resource.tags.comma" : "Please confirm the usage of comma/semicolon in your tags.",
   "post.resource.title" : "title",
   "post.resource.url" : "url",
   "post.resource.viewablefor" : "viewable for",
   "post.resource.waitingForTags" : "fetching recommended tags",
   "posts" : "posts",
   "posts.refresh" : "refresh posts",
   "previous" : "&lt;",
   "privacy" : "privacy",
   "publications" : "publications",
   "purposes" : "purposes",
   "ranking.method" : "ranking",
   "ranking.normalize" : "normalize",
   "ranking.normalized" : "normalized",
   "ranking.not_normalized" : "not normalized",
   "ranking.tag_overlap" : "tag overlap",
   "ranking.tfidf" : "tfidf",
   "register.confirmationMail" : "A confirmation message has been sent to your email address.",
   "register.dragButtons" : "Drag the buttons with the mouse into your browser toolbar.",
   "register.internetExplorer" : "For Internet Explorer you have to right-click the button and select \"add to favorites\". More infos",
   "register.internetExplorer.here" : "here",
   "register.nextSteps" : "Next steps:",
   "register.nextSteps.step1" : "Drag these buttons to the links toolbar of your browser.",
   "register.nextSteps.step2.click" : "Afterwards a click on \"my{0}\" shows your first successful bookmark.",
   "register.nextSteps.step2.surf" : "Surf to your favourite page and bookmark it by clicking on the newly added \"post bookmark\" button.",
   "register.notice.openid" : "Register to BibSonomy using OpenID",
   "register.openid.desc" : "OpenID is a new open standard that lets you sign in to web sites with a single URL that you own.\\nThis URL can be your homepage or blog, or it can be provided to you by a web site you use. \\nIn either case, you only have to sign in once to your OpenID provider and so you only need to maintain a single password.",
   "register.openid.desc.title" : "What is OpenID?",
   "register.openid.example" : "(e.g. http://username.myopenid.com)",
   "register.openid.hint1" : "Alternatively,",
   "register.openid.hint2" : "register using OpenID.",
   "register.openid.hint3" : "It's easier, and you won't need to remember a new username and password.",
   "register.openid.optional" : "Optional Information",
   "register.openid.required" : "Required Information",
   "register.openid.step1" : "Step 1 - Insert your OpenID below",
   "register.openid.step2" : "Step 2 - Edit profile data",
   "register.signedIn" : "You have successfully signed in.",
   "register.success" : "You successfully registered as user {0}!",
   "register.welcome" : "Welcome to",
   "relatedtags" : "related tags",
   "relatedusers" : "related users",
   "reminder.helptext" : "If you have lost your password you can request a new one with this formular. You will receive an email with the automatically generated password which you use to login the next time.",
   "resetbutton" : "reset",
   "save" : "save",
   "settings.aboutMe" : "about me",
   "settings.add" : "add",
   "settings.addFriendsNow" : "{0} friends now",
   "settings.addagroup" : "add a group",
   "settings.addgroupdescription" : "If you want a group added to the system, create a user account with the desired group name and write an E-Mail to {0}",
   "settings.adduser" : "add user",
   "settings.addusertomygroup" : "add user to my group",
   "settings.alphabet" : "alphabet",
   "settings.apidoc" : "API Documentation",
   "settings.apisupport" : "BibSonomy now provides {0} access for all users. Just click the button below to get access. Your generated API key will be displayed here.  \\u0009\\u0009\\u0009\\u0009\\u0009",
   "settings.birthday" : "birthday",
   "settings.cancel" : "cancel",
   "settings.cancelJoinRequest" : "cancel join request for user {0}",
   "settings.change" : "change",
   "settings.changepassword" : "change password",
   "settings.cloud" : "cloud",
   "settings.confirmpassword" : "(please confirm password)",
   "settings.contact" : "contact",
   "settings.currentpassword" : "current password",
   "settings.deleteaccount" : "delete account",
   "settings.deletemyaccount" : "delete my account",
   "settings.delicious.header" : "import your Delicious data:",
   "settings.delicious.hint" : "group settings will be transferred from Delicious",
   "settings.delicious.overwrite" : "Delicious bookmarks overwrite {0} bookmarks",
   "settings.disabled" : "disabled",
   "settings.email" : "email",
   "settings.enabled" : "enabled",
   "settings.english" : "english",
   "settings.female" : "female",
   "settings.firefox.button.text" : "import bookmarks",
   "settings.firefox.fileselect" : "select your file:",
   "settings.firefox.header" : "import your bookmarks from Firefox",
   "settings.firefox.newBookmarks" : "The following Bookmarks were imported successfully",
   "settings.firefox.nonImportedBookmarks" : "The following Bookmarks could not import because they already exist in the system. Please use the overwrite functionality",
   "settings.firefox.overwrite" : "Firefox bookmarks overwrite {0} bookmarks",
   "settings.firefox.updatedBookmarks" : "The following Bookmarks were updated successfully",
   "settings.firefox.viewalble" : "viewable for",
   "settings.frequency" : "frequency",
   "settings.friendOf" : "I'm a friend of",
   "settings.friends" : "friends",
   "settings.gender" : "gender",
   "settings.generalInformation" : "general information",
   "settings.generateapikey" : "(re)generate API key",
   "settings.german" : "german",
   "settings.group" : "group",
   "settings.hobbies" : "hobbies",
   "settings.homepage" : "homepage",
   "settings.jabref.beginning" : "(appears at the beginning of the output, optional)",
   "settings.jabref.end" : "(appears at the end of the output, optional)",
   "settings.jabref.explain" : "For an explanation on how to write such export filters, have a look at the <a href",
   "settings.jabref.item" : "(used to render each publication item)",
   "settings.list" : "list",
   "settings.logclicks" : "log clicks to external pages",
   "settings.logging" : "logging",
   "settings.male" : "male",
   "settings.mandatory" : "mandatory; not included in your public profile",
   "settings.memberlistis" : "member list is",
   "settings.myFriends" : "my friends",
   "settings.myFriendsAre" : "my {0} are",
   "settings.newpassword" : "new password",
   "settings.no" : "no",
   "settings.noFriends" : "no friends found",
   "settings.notloggedinwithgroupaccount" : "Sorry, you're not logged in with the corresponding group account. Please {0} as user {1}.",
   "settings.openURLDescription" : "a URL to your local {0} resolver",
   "settings.passwordwithoutspaces" : "(required :: without spaces)",
   "settings.place" : "place",
   "settings.privacylevel" : "privacy level",
   "settings.private" : "private",
   "settings.profession" : "profession",
   "settings.profileInfo" : "The information you enter here can be accessed via {0}. This feature is experimental and will be extended in the future. With \"{1}\" you can adjust who can see this information.",
   "settings.profileViewableFor" : "profile viewable for",
   "settings.public" : "public",
   "settings.publicformembers" : "public for members",
   "settings.questionsregardingapi" : "Refer to the {0} or write an email to {1} if you have questions or comments.\\u0009",
   "settings.really" : "really",
   "settings.realname" : "real name",
   "settings.reason" : "reason",
   "settings.saveChanges" : "save changes",
   "settings.scientificInterests" : "scientific interests",
   "settings.setlayout" : "set layout",
   "settings.shareddocuments" : "shared documents",
   "settings.shareddocumentsare" : "shared documents are",
   "settings.styleSettingsHeader" : "adapt the layout of your tag box and post lists",
   "settings.tag.defaultLanguage" : "default language",
   "settings.tag.itemsPerPage" : "show that many items per page",
   "settings.tag.onlyMinFreq" : "show only tags with minimal frequency",
   "settings.tag.showAs" : "show tags as",
   "settings.tag.showTooltipsForTags" : "show tooltips for tags",
   "settings.tag.sortBy" : "sort tags by",
   "settings.updatesettings" : "update settings",
   "settings.username" : "user name",
   "settings.yes" : "yes",
   "settings.yestodeleteaccount" : "(type {0} to delete your account)",
   "settings.yourapikey" : "Your API key is:\\u0009",
   "show" : "show",
   "similartags" : "similar tags",
   "sort.date" : "date",
   "sort.folkrank" : "folkrank",
   "sort.folkrank.weight" : "weight",
   "sort.orderBy" : "order by",
   "statistic" : "statistics",
   "submit" : "submit",
   "system.about" : "{0} is a system for sharing bookmarks and lists of literature. When discovering a bookmark or a publication on the web, you can store it on our server. You can add tags to your post to retrieve it more easily. This is very similar to the bookmarks/favorites that you store within your browser. The advantage of {0} is that you can access your data from  whereever you are. Furthermore, you can discover more bookmarks and publications from your friends and other people.",
   "system.contact" : "Contact:",
   "system.desc" : "A blue social bookmark and publication sharing system.",
   "system.groups" : "If you want a group added to the system, create a user account with the desired group name and write an e-mail to <a href",
   "system.introduction" : "This page shows you the latest updates of {0}. Why don't you just try it yourself? After a free <a href",
   "system.offeredBy" : "{0} is offered by the <a href",
   "tag" : "tag",
   "tag.addRelatedTag" : "+",
   "tag.asConceptFrom" : "as concept from",
   "tag.asConceptFromAll" : "as concept from all users",
   "tag.asConceptFromGroup" : "as concept from group",
   "tag.asTagFrom" : "as tag from",
   "tag.asTagFromAll" : "as tag from all users",
   "tag.asTagFromGroup" : "as tag from group",
   "tag.relatedness" : "relatedness",
   "tagbox.alph" : "alpha",
   "tagbox.cloud" : "cloud",
   "tagbox.freq" : "freq",
   "tagbox.list" : "list",
   "tagbox.minfreq" : "minfreq",
   "tagrelations" : "relations",
   "tagrelations.all.text.partOne" : "Here you can see the most popular relations of our users.",
   "tagrelations.all.text.partTwo" : "You can access your own relations via {0} and edit them on the {1} page.",
   "tagrelations.all.title" : "get an overview of all tag relations",
   "tagrelations.group.title" : "get an overview of the relations of this group",
   "tagrelations.hide" : "&darr;",
   "tagrelations.hide.title" : "hide relation",
   "tagrelations.hideAll" : "hide all",
   "tagrelations.hideAll.title" : "hide all relations",
   "tagrelations.show.itemspercount" : "Currenty showing {0} concepts per page.",
   "tagrelations.show.itemspercount.count" : "Show {0}, {1}, {2}, {3} concepts per page.",
   "tagrelations.showAll" : "show all",
   "tagrelations.showAll.title" : "show all relations",
   "tagrelations.showPostsForConcept.title" : "show all posts which have {0} or one of its subtags attached",
   "tagrelations.user.title" : "get an overview of the relations of this user",
   "tags" : "tags",
   "tags.highlighted.by_user" : "'s tags highlighted",
   "tags.of_resource" : "tags of this resource",
   "text" : "text",
   "typeMismatch.java.net.URL" : "Please enter a valid URL. Usually it begins with \"http://\".",
   "user" : "user",
   "user.settings.birthday" : "birthday",
   "user.settings.email" : "email",
   "user.settings.homepage" : "homepage",
   "user.settings.openid" : "OpenID",
   "user.settings.passwordCheck" : "password",
   "user.settings.realname" : "realname",
   "user.tmp.password" : "temporary password",
   "users" : "users",
   "users.similar" : "similar users",
   "users.similar.for" : "{0}&#39;s similar users",
   "users.similar.your" : "your similar users",
   "yes" : "yes",
   "younger" : "younger"
}
