//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.29 at 08:11:06 PM CET 
//


package org.bibsonomy.database.systemstags.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SystemTagsCollection_QNAME = new QName("", "systemTagsCollection");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemTagsCollection }
     * 
     */
    public SystemTagsCollection createSystemTagsCollection() {
        return new SystemTagsCollection();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link SystemTagType }
     * 
     */
    public SystemTagType createSystemTagType() {
        return new SystemTagType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemTagsCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "systemTagsCollection")
    public JAXBElement<SystemTagsCollection> createSystemTagsCollection(SystemTagsCollection value) {
        return new JAXBElement<SystemTagsCollection>(_SystemTagsCollection_QNAME, SystemTagsCollection.class, null, value);
    }

}
