ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool1 "cd apitest; perl perf_test.pl 10 >> log/kde-pool1.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool2 "cd apitest; perl perf_test.pl 10 >> log/kde-pool2.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool3 "cd apitest; perl perf_test.pl 10 >> log/kde-pool3.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool4 "cd apitest; perl perf_test.pl 10 >> log/kde-pool4.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool5 "cd apitest; perl perf_test.pl 10 >> log/kde-pool5.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool6 "cd apitest; perl perf_test.pl 10 >> log/kde-pool6.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool7 "cd apitest; perl perf_test.pl 10 >> log/kde-pool7.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool8 "cd apitest; perl perf_test.pl 10 >> log/kde-pool8.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool11 "cd apitest; perl perf_test.pl 10 >> log/kde-pool11.output &" &
ssh -i /home/dbenz/.ssh/id_rsa dbe@kde-pool12 "cd apitest; perl perf_test.pl 10 >> log/kde-pool12.output &" &
