package org.bibsonomy.search.es.management.post;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.bibsonomy.model.GoldStandardBookmark;
import org.bibsonomy.model.Post;
import org.bibsonomy.model.ResultList;
import org.bibsonomy.search.es.EsSpringContextWrapper;
import org.bibsonomy.search.es.search.post.ElasticsearchPostSearch;
import org.bibsonomy.search.es.testutil.AbstractCommunityPostSearchTest;
import org.junit.Test;

/**
 * tests for the {@link ElasticsearchCommunityPostManager} of the bookmark entries
 *
 * @author dzo
 */
public class ElasticsearchCommunityPostBookmarkManagerITCase extends AbstractCommunityPostSearchTest<GoldStandardBookmark> {

	private static final ElasticsearchPostSearch<GoldStandardBookmark> COMMUNITY_BOOKMARK_SEARCH = EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityBookmarkSearch", ElasticsearchPostSearch.class);

	@Test
	public void testGenerate() {
		// the indices are generated by the abstract class

		// check if gold standard publications are indexed
		final ResultList<Post<GoldStandardBookmark>> communityResults = COMMUNITY_BOOKMARK_SEARCH.getPosts(null, null, null, null, null, null, "Universität Kassel", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(communityResults.size(), is(1));

		// check if also normal posts are indexed
		final ResultList<Post<GoldStandardBookmark>> normalPosts = COMMUNITY_BOOKMARK_SEARCH.getPosts(null, null, null, null, null, null, "KDE", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(normalPosts.size(), is(1));
		assertThat(normalPosts.getTotalCount(), is(1));

		final Post<GoldStandardBookmark> firstResult = normalPosts.get(0);
		assertThat(firstResult.getResource().getTitle(), is("kde"));
	}

	@Test
	public void testUpdate() {
		// TODO: add tests for updating the index

		// unmark a user

		// delete user (mark as spammer)

		// delete a community post

		// delete a publication

		// insert a new publication

		// insert a new communitypost
	}

	@Override
	protected ElasticsearchCommunityPostManager<GoldStandardBookmark> getManager() {
		return EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityBookmarkManager", ElasticsearchCommunityPostManager.class);
	}
}