package org.bibsonomy.search.es.management.post;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.bibsonomy.model.GoldStandardPublication;
import org.bibsonomy.model.Post;
import org.bibsonomy.model.ResultList;
import org.bibsonomy.search.es.EsSpringContextWrapper;
import org.bibsonomy.search.es.search.post.EsResourceSearch;
import org.bibsonomy.search.es.testutil.AbstractCommunityPostSearchTest;
import org.junit.Test;

/**
 * tests for the {@link ElasticsearchCommunityManager} of the publication entries
 *
 * @author dzo
 */
public class ElasticsearchCommunityManagerPublicationITCase extends AbstractCommunityPostSearchTest<GoldStandardPublication> {

	private static final EsResourceSearch<GoldStandardPublication> COMMMUNITY_PUBLICATION_SEARCH = EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityPublicationSearch", EsResourceSearch.class);

	@Test
	public void testGenerate() {
		// the indices are generated by the abstract class

		// check if gold standard publications are indexed
		final ResultList<Post<GoldStandardPublication>> communityResults = COMMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "test title", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(communityResults.size(), is(1));

		// check if also normal posts are indexed
		final ResultList<Post<GoldStandardPublication>> normalPosts = COMMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "ontologies", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(normalPosts.size(), is(1));
		assertThat(normalPosts.getTotalCount(), is(1));

		final Post<GoldStandardPublication> firstResult = normalPosts.get(0);
	}

	@Test
	public void testUpdate() {



		// TODO: add tests for updating the index

		// unmark a user

		// delete user (mark as spammer)

		// delete a community post

		// delete a publication

		// insert a new publication

		// insert a new communitypost


	}

	@Override
	protected ElasticsearchCommunityManager<GoldStandardPublication> getManager() {
		return EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityPublicationManager", ElasticsearchCommunityManager.class);
	}
}