package org.bibsonomy.search.es.management.post;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.bibsonomy.database.managers.AdminDatabaseManager;
import org.bibsonomy.database.managers.BibTexDatabaseManager;
import org.bibsonomy.database.managers.GoldStandardPublicationDatabaseManager;
import org.bibsonomy.model.BibTex;
import org.bibsonomy.model.GoldStandardPublication;
import org.bibsonomy.model.PersonName;
import org.bibsonomy.model.Post;
import org.bibsonomy.model.ResultList;
import org.bibsonomy.model.Tag;
import org.bibsonomy.model.User;
import org.bibsonomy.model.factories.ResourceFactory;
import org.bibsonomy.model.util.BibTexUtils;
import org.bibsonomy.model.util.GroupUtils;
import org.bibsonomy.search.es.EsSpringContextWrapper;
import org.bibsonomy.search.es.search.post.EsResourceSearch;
import org.bibsonomy.search.es.testutil.AbstractCommunityPostSearchTest;
import org.bibsonomy.util.Sets;
import org.junit.Test;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 * tests for the {@link ElasticsearchCommunityManager} of the publication entries
 *
 * @author dzo
 */
public class ElasticsearchCommunityManagerPublicationITCase extends AbstractCommunityPostSearchTest<GoldStandardPublication> {

	private static final EsResourceSearch<GoldStandardPublication> COMMUNITY_PUBLICATION_SEARCH = EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityPublicationSearch", EsResourceSearch.class);

	private static final ElasticsearchCommunityManager<GoldStandardPublication> MANAGER = EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityPublicationManager", ElasticsearchCommunityManager.class);

	private static final GoldStandardPublicationDatabaseManager GOLD_STANDARD_PUBLICATION_DATABASE_MANAGER = testDatabaseContext.getBean(GoldStandardPublicationDatabaseManager.class);

	private static final BibTexDatabaseManager PUBLICATION_DATABASE_MANAGER = testDatabaseContext.getBean(BibTexDatabaseManager.class);

	private static final AdminDatabaseManager ADMIN_DATABASE_MANAGER = testDatabaseContext.getBean(AdminDatabaseManager.class);

	@Test
	public void testGenerate() {
		// the indices are generated by the abstract class

		// check if gold standard publications are indexed
		final ResultList<Post<GoldStandardPublication>> communityResults = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "test title", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(communityResults.size(), is(3));

		// check if also normal posts are indexed
		final ResultList<Post<GoldStandardPublication>> normalPosts = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "ontologies", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(normalPosts.size(), is(1));
		assertThat(normalPosts.getTotalCount(), is(1));

		final Post<GoldStandardPublication> firstResult = normalPosts.get(0);
		assertThat(firstResult.getResource().getTitle(), is("A case for abductive reasoning over ontologies"));
	}

	@Test
	public void testUpdate() {
		final String searchTerms = "Wurst aufs Brot";
		final ResultList<Post<GoldStandardPublication>> communityPosts = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, searchTerms, null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(communityPosts.size(), is(1));

		final Post<GoldStandardPublication> goldStandardPublicationPost = communityPosts.get(0);
		final GoldStandardPublication publication = goldStandardPublicationPost.getResource();
		final String interHash = publication.getInterHash();
		final String intraHash = publication.getIntraHash();

		final String testuser1 = "testuser1";
		final User loggedinUser = new User(testuser1);
		final boolean deleted = GOLD_STANDARD_PUBLICATION_DATABASE_MANAGER.deletePost("", interHash, loggedinUser, this.dbSession);
		assertThat(deleted, is(true));

		this.updateIndex();

		final List<Post<GoldStandardPublication>> afterCommunityDelete = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, searchTerms, null, null, null, null, null, null, null, null, null, 10, 0);

		// deleting the community post should do nothing, if at least one user has the publication in his/her collection
		assertThat(afterCommunityDelete.size(), is(1));

		final boolean userPostDeleted = PUBLICATION_DATABASE_MANAGER.deletePost("testuserP", intraHash, loggedinUser, this.dbSession);
		assertThat(userPostDeleted, is(true));

		this.updateIndex();

		final List<Post<GoldStandardPublication>> afterNormalPostDelete = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, searchTerms, null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(afterNormalPostDelete.size(), is(0));

		/*
		 * insert a new publication
		 */
		final Post<BibTex> publicationPost = generateTestPost(BibTex.class);
		publicationPost.setUser(loggedinUser);
		final boolean posted = PUBLICATION_DATABASE_MANAGER.createPost(publicationPost, loggedinUser, this.dbSession);

		assertThat(posted, is(true));

		this.updateIndex();

		final ResultList<Post<GoldStandardPublication>> postsAfterCreating = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, publicationPost.getResource().getTitle(), null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(postsAfterCreating.size(), is(1));

		/*
		 * insert a new communitypost
		 */
		final Post<GoldStandardPublication> newGoldstandardPost = generateTestPost(GoldStandardPublication.class);
		final String publicationAbstract = "abstract";
		newGoldstandardPost.getResource().setAbstract(publicationAbstract);

		GOLD_STANDARD_PUBLICATION_DATABASE_MANAGER.createPost(newGoldstandardPost, loggedinUser, this.dbSession);

		this.updateIndex();

		final ResultList<Post<GoldStandardPublication>> postsAfterCommunityCreating = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, publicationPost.getResource().getTitle(), null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(postsAfterCommunityCreating.size(), is(1));
		assertThat(postsAfterCommunityCreating.get(0).getResource().getAbstract(), is(publicationAbstract));

		final ResultList<Post<GoldStandardPublication>> testuser3PostsInIndex = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "test friend title", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(testuser3PostsInIndex.size(), is(1));

		// mark user as spammer
		final String userToFlag = "testuser3";
		final User user = new User(userToFlag);
		user.setSpammer(Boolean.TRUE);
		user.setAlgorithm("unittest");
		ADMIN_DATABASE_MANAGER.flagSpammer(user, "admin", this.dbSession);

		this.updateIndex();

		final ResultList<Post<GoldStandardPublication>> testuser3PostsInIndexAfterMarkedAsSpammer = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "test friend title", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(testuser3PostsInIndexAfterMarkedAsSpammer.size(), is(0));

		// unmark a user
		user.setSpammer(Boolean.FALSE);
		user.setAlgorithm("admin");
		user.setPrediction(null); // FIXME: side effects :(
		ADMIN_DATABASE_MANAGER.flagSpammer(user, "admin", this.dbSession);

		this.updateIndex();

		final ResultList<Post<GoldStandardPublication>> testuser3PostsInIndexAfterUnmarkedAsSpammer = COMMUNITY_PUBLICATION_SEARCH.getPosts(userToFlag, null, null, null, null, null, "test friend title", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(testuser3PostsInIndexAfterUnmarkedAsSpammer.size(), is(1));

		final Post<GoldStandardPublication> firstResultTestuser3 = testuser3PostsInIndexAfterUnmarkedAsSpammer.get(0);

		final List<User> users = firstResultTestuser3.getUsers();
		assertThat(users.size(), is(1));

		final ResultList<Post<GoldStandardPublication>> beforeDeleteTestuser1 = COMMUNITY_PUBLICATION_SEARCH.getPosts(testuser1, null, null, null, null, null, "Firefly", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(beforeDeleteTestuser1.size(), is(1));
		assertThat(beforeDeleteTestuser1.get(0).getUsers().size(), is(1));

		final boolean deletedNormalPost = PUBLICATION_DATABASE_MANAGER.deletePost(testuser1, "6ce5d533a44887f2d2730fe7866f8fd0", loggedinUser, this.dbSession);
		assertThat(deletedNormalPost, is(true));

		this.updateIndex();

		final ResultList<Post<GoldStandardPublication>> afterDeleteTestuser1 = COMMUNITY_PUBLICATION_SEARCH.getPosts(testuser1, null, null, null, null, null, "Firefly", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(afterDeleteTestuser1.size(), is(1));
		assertThat(afterDeleteTestuser1.get(0).getUsers().size(), is(0));
	}

	private static <P extends BibTex> Post<P> generateTestPost(final Class<? extends P> clazz) {
		final Post<P> publicationPost = new Post<>();
		final ResourceFactory factory = new ResourceFactory();
		final P publication = factory.createPublication(clazz);
		publicationPost.setTags(Sets.asSet(new Tag("test")));
		publicationPost.setGroups(Sets.asSet(GroupUtils.buildPublicGroup()));
		publication.setYear("2018");
		publication.setTitle("Firefly");
		publication.setBibtexKey(BibTexUtils.generateBibtexKey(publication));
		publication.setAuthor(Arrays.asList(new PersonName("Book", "Shepherd")));
		publication.setEntrytype(BibTexUtils.ARTICLE);
		publication.recalculateHashes();
		publicationPost.setResource(publication);
		final Date date = new Date();
		publicationPost.setDate(date);
		publicationPost.setChangeDate(date);
		return publicationPost;
	}

	@Override
	protected ElasticsearchCommunityManager<GoldStandardPublication> getManager() {
		return MANAGER;
	}
}