package org.bibsonomy.search.es.management.post;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.bibsonomy.database.managers.BibTexDatabaseManager;
import org.bibsonomy.database.managers.GoldStandardPublicationDatabaseManager;
import org.bibsonomy.model.GoldStandardPublication;
import org.bibsonomy.model.Post;
import org.bibsonomy.model.ResultList;
import org.bibsonomy.model.User;
import org.bibsonomy.search.es.EsSpringContextWrapper;
import org.bibsonomy.search.es.search.post.EsResourceSearch;
import org.bibsonomy.search.es.testutil.AbstractCommunityPostSearchTest;
import org.junit.Test;

import java.util.List;

/**
 * tests for the {@link ElasticsearchCommunityManager} of the publication entries
 *
 * @author dzo
 */
public class ElasticsearchCommunityManagerPublicationITCase extends AbstractCommunityPostSearchTest<GoldStandardPublication> {

	private static final EsResourceSearch<GoldStandardPublication> COMMUNITY_PUBLICATION_SEARCH = EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityPublicationSearch", EsResourceSearch.class);

	private static final ElasticsearchCommunityManager<GoldStandardPublication> MANAGER = EsSpringContextWrapper.getContext().getBean("elasticsearchCommunityPublicationManager", ElasticsearchCommunityManager.class);

	private static final GoldStandardPublicationDatabaseManager GOLD_STANDARD_PUBLICATION_DATABASE_MANAGER = testDatabaseContext.getBean(GoldStandardPublicationDatabaseManager.class);

	private static final BibTexDatabaseManager PUBLICATION_DATABASE_MANAGER = testDatabaseContext.getBean(BibTexDatabaseManager.class);

	@Test
	public void testGenerate() {
		// the indices are generated by the abstract class

		// check if gold standard publications are indexed
		final ResultList<Post<GoldStandardPublication>> communityResults = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "test title", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(communityResults.size(), is(3));

		// check if also normal posts are indexed
		final ResultList<Post<GoldStandardPublication>> normalPosts = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "ontologies", null, null, null, null, null, null, null, null, null, 10, 0);
		assertThat(normalPosts.size(), is(1));
		assertThat(normalPosts.getTotalCount(), is(1));

		final Post<GoldStandardPublication> firstResult = normalPosts.get(0);
		assertThat(firstResult.getResource().getTitle(), is("A case for abductive reasoning over ontologies"));
	}

	@Test
	public void testUpdate() {
		final ResultList<Post<GoldStandardPublication>> communityPosts = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "Wurst aufs Brot", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(communityPosts.size(), is(1));

		final Post<GoldStandardPublication> goldStandardPublicationPost = communityPosts.get(0);
		final GoldStandardPublication publication = goldStandardPublicationPost.getResource();
		final String interHash = publication.getInterHash();
		final String intraHash = publication.getIntraHash();

		final User loggedinUser = new User("testuser1");
		final boolean deleted = GOLD_STANDARD_PUBLICATION_DATABASE_MANAGER.deletePost("", interHash, loggedinUser, this.dbSession);
		assertThat(deleted, is(true));

		this.updateIndex();

		final List<Post<GoldStandardPublication>> afterCommunityDelete = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "title1", null, null, null, null, null, null, null, null, null, 10, 0);

		// deleting the community post shoud do nothing, if at least one user
		assertThat(afterCommunityDelete, is(1));

		final boolean userPostDeleted = PUBLICATION_DATABASE_MANAGER.deletePost("testuserP", intraHash, loggedinUser, this.dbSession);
		assertThat(userPostDeleted, is(true));

		final List<Post<GoldStandardPublication>> afterNormalPostDelete = COMMUNITY_PUBLICATION_SEARCH.getPosts(null, null, null, null, null, null, "title1", null, null, null, null, null, null, null, null, null, 10, 0);

		assertThat(afterNormalPostDelete.size(), is(0));

		// TODO: add tests for updating the index

		// unmark a user

		// delete user (mark as spammer)

		// delete a community post

		// delete a publication

		// insert a new publication

		// insert a new communitypost


	}

	@Override
	protected ElasticsearchCommunityManager<GoldStandardPublication> getManager() {
		return MANAGER;
	}
}