package org.bibsonomy.search.es.index;

import java.io.IOException;

import org.bibsonomy.model.BibTex;
import org.bibsonomy.search.es.ESConstants;
import org.bibsonomy.search.es.ESConstants.Fields;
import org.elasticsearch.common.xcontent.XContentBuilder;

/**
 * mapping builder for indexed {@link BibTex}
 *
 * @author dzo
 */
public class PublicationMappingBuilder extends ResourceMappingBuilder<BibTex> {

	/**
	 * @param resourceType
	 */
	public PublicationMappingBuilder(Class<BibTex> resourceType) {
		super(resourceType);
	}

	/* (non-Javadoc)
	 * @see org.bibsonomy.search.es.index.ResourceMapping#doResourceSpecificMapping(org.elasticsearch.common.xcontent.XContentBuilder)
	 */
	@Override
	protected void doResourceSpecificMapping(XContentBuilder builder) throws IOException {
		builder
			.startObject(Fields.Publication.ADDRESS)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(Fields.Publication.ANNOTE)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(Fields.Publication.AUTHOR)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.KEY)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.ABSTRACT)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(Fields.Publication.BIBTEXKEY)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.BOOKTITLE)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.CHAPTER)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(Fields.Publication.CROSSREF)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(Fields.Publication.DAY)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.EDITION)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.EDITOR)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.ENTRY_TYPE)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.HOWPUBLISHED)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.INSTITUTION)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.JOURNAL)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.MISC)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.MONTH)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.NOTE)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.NUMBER)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.ORGANIZATION)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.PAGES)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.PRIVNOTE)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INCLUDE_IN_ALL_FIELD, false)
				.field("copy_to", Fields.PRIVATE_ALL_FIELD)
				.field("store", "false") // TODO: remove?
			.endObject()
			.startObject(Fields.PRIVATE_ALL_FIELD)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.PUBLISHER)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.SCHOOL)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.Publication.SERIES)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.TYPE)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.URL)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(Fields.Publication.VOLUME)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_INDEXED)
			.endObject()
			.startObject(Fields.Publication.YEAR)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_ANALYZED)
				.field(INCLUDE_IN_ALL_FIELD, true)
			.endObject()
			.startObject(ESConstants.NORMALIZED_ENTRY_TYPE_FIELD_NAME)
				.field(TYPE_FIELD, STRING_TYPE)
				.field(INDEX_FIELD, NOT_ANALYZED)
			.endObject()
			.startObject(ESConstants.AUTHOR_ENTITY_NAMES_FIELD_NAME)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(ESConstants.AUTHOR_ENTITY_IDS_FIELD_NAME)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(ESConstants.PERSON_ENTITY_NAMES_FIELD_NAME)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject()
			.startObject(Fields.PERSON_ENTITY_IDS_FIELD_NAME)
				.field(TYPE_FIELD, STRING_TYPE)
			.endObject();
	}

}
